# Car Datasets
- Car Company Names: The manufacturer or brand of the car.
- Car Models: The specific name or series of the car.
- Engine Types: Information on engine specifications .
- CC/Battery Capacity: Engine displacement in cubic centimeters or battery capacity for electric cars.
- Horsepower (HP): The power output of the car's engine or motor.
- Top Speed: The maximum speed the car can achieve.
- 0-100 km/h Performance: The time it takes for the car to accelerate from 0 to 100 km/h.
- Price (in USD): The car's price listed in United States dollars.
- Fuel Type: Specifies whether the car uses petrol, diesel, electricity, or hybrid fuel systems.
- Seating Capacity: The number of passengers the car can accommodate.
- Torque: The rotational force the engine generates.

The objetive is to predict the price of the cars

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Reading data set

In [2]:
df = pd.read_csv("../Cars_Datasets_2025.csv", encoding="latin-1")

## EDA

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Names              1218 non-null   str
 1   Cars Names                 1218 non-null   str
 2   Engines                    1218 non-null   str
 3   CC/Battery Capacity        1215 non-null   str
 4   HorsePower                 1218 non-null   str
 5   Total Speed                1218 non-null   str
 6   Performance(0 - 100 )KM/H  1212 non-null   str
 7   Cars Prices                1218 non-null   str
 8   Fuel Types                 1218 non-null   str
 9   Seats                      1218 non-null   str
 10  Torque                     1217 non-null   str
dtypes: str(11)
memory usage: 104.8 KB

### Multiple null values found in the next columns
- CC/Battery Capacity: 3 nulls
- Performance(0 - 100 )KM/H: 6 nulls
- Torque: 1 nulls

In [4]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

## Company Names column

In [5]:
df["Company Names"].value_counts().sort_index()

Company Names
ASTON MARTIN          11
AUDI                  21
Acura                 27
BENTLEY                1
BMW                   41
Bugatti               10
Cadillac              20
Chevrolet             58
FERRARI                9
Ford                  54
GMC                   59
HONDA                  7
HYUNDAI               23
Jaguar Land Rover     40
Jeep                  19
KIA                   16
KIA                    1
Kia                   54
LAMBORGHINI           24
MAHINDRA               3
MARUTI SUZUKI          3
MERCEDES              21
Mazda                 87
Mitsubishi            60
NISSAN                10
Nissan               149
Peugeot               54
Porsche               96
ROLLS ROYCE           29
ROLLS ROYCE            1
TOYOTA                45
Tata Motors           29
Tesla                 10
Toyota                 5
VOLVO                  3
Volkswagen           109
Volvo                  9
Name: count, dtype: int64

### `Company Names`column. Multiple companys repeat with the same names
- Nissan / NISSAN
- Toyota / TOYOTA
- Kia / KIA / KIA
- ROLLS ROYCE / ROLLS ROYCE
- Volvo / volvo

## Car names column

In [6]:
def repeated_values(column):
    values = sorted(column.unique())
    values_set = set()
    j = 0
    for i in range(1, len(values)):
        if values[i].lower().strip() == values[j].lower().strip():
            if values[i] not in values_set:
                values_set.add(values[i])
        i = i + 1
        j = j + 1
    return values_set

In [7]:
values_set = repeated_values(df["Cars Names"])
print(values_set)

{'Panamera 4S '}

In [8]:
print(df["Cars Names"].value_counts().sort_index().to_string())

Cars Names
 GT 63 S                                   1
100NX                                      1
114D                                       1
114D SPORT LINE                            1
114i                                       1
116D                                       1
116D ADVANTAGE                             1
116D EFFICIENTDYNAMICS                     1
116i                                       1
116i EFFICIENTDYNAMICS                     1
118D                                       1
118D SPORT LINE                            1
118i                                       1
118i M SPORT                               1
118i SHADOW LINE                           1
118i SPORTLINE                             1
118i URBAN LINE                            1
118i XDRIVE                                1
1200                                       1
120D EFFICIENTDYNAMICS                     1
120D XDRIVE                                1
120i                                       1
120i M SPORT                               1
120i XDRIVE                                1
121                                        1
125D                                       1
125i                                       1
128ti                                      1
1500                                       1
180SX                                      1
2008                                       1
2008 Active                                1
2008 Allure                                1
2008 GT                                    1
200SX                                      2
208                                        1
208 Allure Premium                         1
208 GTI                                    1
208 PSE (Peugeot Sport Engineered)         1
208 Sedan                                  1
280ZX                                      1
3008                                       1
3008 Active                                1
3008 Allure                                1
3008 Allure Premium                        1
3008 GT                                    1
3008 GT Hybrid                             1
3008 GT Line                               1
3008 Hybrid4                               1
3008 PSE                                   1
3008 Plug-In Hybrid                        1
300ZX                                      1
300ZX Turbo                                1
301                                        1
301 Sedan                                  1
308                                        1
308 Allure                                 1
308 GTI                                    1
308 PSE                                    1
308 Saloon                                 1
323F                                       1
330i                                       1
370Z                                       1
370Z NISMO                                 1
370Z Roadster                              1
430i COUPE                                 1
4RUNNER                                    1
4Runner (6th Gen)                          1
5008                                       1
5008 Active                                1
5008 Allure                                1
5008 Allure Premium                        1
5008 GT                                    1
5008 GT Hybrid                             1
5008 GT Line                               1
508                                        1
508 Allure                                 1
508 GT                                     1
508 Hybrid4                                1
508 PSE                                    1
508 PSE (Peugeot Sport Engineered)         2
508 Plug-In Hybrid                         1
508 SW (Station Wagon)                     1
508 Saloon                                 1
530i                                       1
626                                        1
718 Boxster                                1
718 Boxster GTS                            1
718 Boxster T                              1
718 Cayman                                 1
718 Cayman GT4                             1
718 Cayman GT4 RS                          1
718 Cayman S                               1
718 Spyder                                 1
787B (Race Car)                            1
812 GTS                                    1
818                                        1
911 Carrera                                1
911 Carrera 4                              2
911 Carrera 4 GTS                          1
911 Carrera 4S                             1
911 Carrera Base                           1
911 Carrera GTS Lightweight                1
911 Carrera S                              1
911 Carrera S Cabriolet                    1
911 Dakar                                  1
911 Dakar Limited Edition                  1
911 Dakar Sport                            1
911 GT2 RS                                 1
911 GT3                                    1
911 GT3 Cup                                1
911 GT3 RS                                 1
911 GT3 RS Clubsport                       1
911 GT3 Touring                            1
911 GT4 RS                                 1
911 RSR (Motorsport Edition)               1
911 Sport Turismo                          1
911 Targa 4                                1
911 Targa 4 GTS                            1
911 Targa 4 Lightweight                    1
911 Turbo                                  1
911 Turbo Cabriolet                        1
911 Turbo Cabriolet Lightweight            1
911 Turbo Exclusive Series                 1
911 Turbo S                                1
911 Turbo S Coupe                          1
929                                        1
A4                                         1
A5 COUPE                                   1
A6                                         1
A7                                         1
A8                                         1
ACCORD                                     1
AD Wagon                                   1
ALPHARD EXECUTIVE LOUNGE                   1
ALTIMA                                     1
ASX (Outlander Sport)                      1
ASX Dynamic                                1
ASX Exceed                                 1
AUDI R8 Gt                                 1
AVALON                                     1
AVENTADOR LP 780-4 ULTIMATE                1
AVENTADOR LP 780-4 ULTIMATE ROADSTER       1
AVENTADOR ROADSTER                         1
AVENTADOR S                                1
AVENTADOR SV                               1
AVENTADOR SVJ                              1
AVENTADOR SVJ ROADSTER                     1
AVENTADOR SVJ XAGO                         1
AVENTADOR ULTIMAE                          1
AYGO X                                     1
AZ-Offroad                                 1
Acadia                                     1
Acadia AT4                                 1
Acadia Black Edition                       1
Acadia Denali                              1
Acadia Denali Ultimate                     1
Acadia SLE                                 1
Accent                                     1
Airtrek                                    1
Almera                                     1
Almera Tino                                1
Altroz                                     1
Altroz CNG                                 1
Altroz DCA                                 1
Altroz iTurbo                              1
Amarok                                     1
Amarok V6                                  1
Amarok V8                                  1
Aria                                       1
Ariya                                      1
Ariya Dual Motor AWD                       1
Ariya E-4ORCE                              1
Ariya Empower+                             1
Ariya Lounge Edition                       1
Ariya Premiere                             1
Armada                                     1
Armada Platinum                            1
Arteon                                     1
Arteon 280 TSI                             1
Arteon 4MOTION                             1
Arteon R-Line                              1
Arteon Shooting Brake                      1
Astina                                     1
Atenza                                     1
Atlas                                      1
Attrage                                    1
Autozam AZ-1                               1
Avenir                                     1
Azera                                      1
B-Series Pickup                            1
BENZ A-CLASS A 45 S                        1
BENZ C-CLASS C 43                          1
BENZ CLA 45 AMG                            1
BENZ CLS 450                               1
BENZ E-CLASS E 350                         1
BENZ E-CLASS E 450                         1
BENZ E-CLASS E 63 S                        1
BENZ EQS 53                                1
BENZ GLA 45                                1
BENZ GLC 350                               1
BENZ GLC 43                                1
BENZ GLE 350                               1
BENZ GLE 450                               1
BENZ GLE 53                                1
BENZ GLE 63 S                              1
BENZ GT 53                                 1
BENZ MAYBACH S 680                         1
BENZ S-CLASS S 350                         1
BENZ S-CLASS S 500                         1
BENZ S-CLASS S 580                         1
BREZZA                                     1
BT-50                                      1
BZ3                                        1
BZ4X                                       1
Beetle                                     1
Beetle Dune                                1
Beetle Final Edition                       1
Biante                                     1
Blazer                                     1
Blazer LT                                  1
Blazer Premier                             1
Blazer RS                                  1
Bluebird Sylphy                            1
Bluebird Z                                 1
Bolide                                     1
Bolt EUV                                   1
Bolt EV                                    1
Bolt EV 2LT                                1
Bolt EV Premier                            1
Bongo Friendee                             1
Bongo Truck                                1
Bongo Van                                  1
Bora                                       1
Boxer                                      1
Boxer L2H2                                 1
Bronco                                     1
Bronco (2024)                              1
Bronco Raptor                              1
Bronco Sport                               1
C-HR                                       1
C-HR+                                      1
CAMRY                                      1
CELICA                                     1
CENTURY SUV                                1
CITY                                       1
CIVIC                                      1
CIVIC HATCHBACK                            1
CIVIC TYPE R                               1
COASTER                                    1
COROLLA                                    1
COROLLA HATCHBACK XSE                      1
COROLLA SEDAN HYBRID                       1
CR-V                                       1
CROWN                                      1
CT4                                        1
CT4-V                                      1
CT4-V Blackwing                            1
CT5                                        1
CT5 Premium Luxury                         1
CT5-V                                      1
CT5-V Blackwing                            1
CULLINAN                                   1
CULLINAN BLACK BADGE                       1
CULLINAN BLACK BADGE SUV                   1
CULLINAN FUX ORANGE                        1
CULLINAN RED DIAMOND                       1
CULLINAN SUV                               1
CX-3                                       1
CX-30                                      1
CX-4                                       1
CX-5                                       1
CX-50                                      1
CX-60                                      1
CX-7                                       1
CX-8                                       1
CX-80                                      1
CX-9                                       1
CX-90                                      1
Cabstar                                    1
Caddy                                      1
Caddy Maxi                                 1
California                                 1
Camaro                                     1
Camaro SS                                  1
Camaro ZL1                                 1
Canter (Truck)                             1
Canyon                                     1
Canyon AT4                                 1
Canyon AT4X                                1
Canyon AT4X Edition 1                      1
Canyon Denali                              1
Canyon Denali Black Edition                1
Canyon Elevation                           1
Canyon SLT                                 1
Capella                                    1
Capella Cargo                              1
Caravan Coach                              1
Carnival EX                                1
Carnival LXS                               1
Carnival MPV EX                            1
Carnival SX Prestige                       1
Carnival Special Edition                   1
Carol                                      1
Carol P360                                 1
Cayenne                                    1
Cayenne Base                               1
Cayenne Coupe                              1
Cayenne Coupe Turbo E-Hybrid               1
Cayenne Diesel (Regional Markets)          1
Cayenne E-Hybrid                           1
Cayenne GTS                                1
Cayenne GTS Coupe                          1
Cayenne Platinum Edition                   1
Cayenne S                                  1
Cayenne S Coupe                            1
Cayenne S Hybrid                           1
Cayenne Turbo                              1
Cayenne Turbo GT                           1
Cayenne Turbo S E-Hybrid                   1
Cayenne Turbo S E-Hybrid Coupe             1
Cedric                                     1
Cedric Special Edition                     1
Centodieci                                 1
Chariot                                    1
Cherokee                                   1
Cherry                                     1
Chiron                                     1
Chiron Noire                               1
Chiron Pur Sport                           1
Chiron Sport                               1
Chiron Super Sport                         1
Cima                                       1
Clipper                                    1
Colorado                                   1
Colorado WT                                1
Colorado ZR2                               1
Colt                                       1
Colt CZC Convertible                       1
Compass                                    1
Compass 4xe                                1
Continental GT Azure                       1
Corolla Cross                              1
Corrado                                    1
Corvette                                   1
Corvette Grand Sport                       1
Corvette Stingray                          1
Cosmo Sport (110S)                         1
Crafter                                    1
Cronos                                     1
Crown Signia                               1
Cube                                       1
Cybertruck                                 1
DAWN                                       1
DAWN BLACK BADGE                           1
DAWN BLACK BADGE ADAMAS                    1
DAWN BLACK BADGE VOLANTE                   1
DAWN CONVERTIBLE                           1
DAWN SILVER BULLET                         1
DB11                                       1
DBS SUPERLEGGERA                           1
DBX                                        1
DZIRE                                      1
Datsun 240Z                                1
Datsun 240Z (Classic)                      1
Datsun 510                                 1
Datsun 510 (Classic)                       1
Delica D:5                                 1
Delica Space Gear                          1
Delica Van                                 1
Demio                                      1
Dion                                       1
Divo                                       1
E-Series Cutaway                           1
E-TRON                                     1
E-TRON SPORTBACK                           1
ELANTRA                                    1
EV6 AWD GT-Line                            1
EV6 First Edition                          1
EV6 First Edition AWD                      1
EV6 GT Performance                         1
EV6 Light                                  1
EV6 Wind                                   1
Eclipse Cross                              1
Eclipse Cross Black Edition                1
Eclipse Cross PHEV                         1
EcoSport                                   1
Edge                                       1
Elantra                                    1
Elantra GT                                 1
Elgrand                                    1
Endeavor                                   1
Equinox                                    1
Equinox LT                                 1
Equinox Premier                            1
Equinox RS                                 1
Equus                                      1
Escalade                                   1
Escalade ESV                               1
Escalade Platinum                          1
Escalade V                                 1
Escape (Kuga)                              1
Escape Hybrid                              1
Escape Plug-in Hybrid (2024)               1
Etude                                      1
Eunos 500                                  1
Eunos Cosmo                                1
Eunos Roadster                             1
Evalia                                     1
Everest                                    1
Expedition                                 1
Expedition King Ranch                      1
Expert                                     1
Expert Electric                            1
Expert L2H1                                1
Explorer                                   1
Explorer (2024)                            1
Explorer Hybrid                            1
Explorer Platinum                          1
Explorer Plug-in Hybrid                    1
F-150                                      1
F-150 Lightning                            1
F-150 Limited                              1
F-150 Platinum                             1
F-150 Raptor                               1
F-250 Super Duty                           1
F-350 Super Duty                           1
F-450 Super Duty                           1
F-550 Super Duty                           1
F8 SPIDER                                  1
F8 TRIBUTO                                 1
FORTUNER GR SPORT                          1
FRONTIER                                   1
Fairlady Z Heritage                        1
Familia Astina                             1
Familia Sedan                              1
Fiesta                                     1
Fiesta ST                                  1
Figaro                                     1
Flex                                       1
Focus                                      1
Focus ST                                   1
Forte EX Premium                           1
Forte FE                                   1

### `Cars Names` 
The next value it's duplicated `Panamera 4S`.

## Engines column

In [9]:
print(repeated_values(df["Engines"]))

{'ELECTRIC '}

In [10]:
print(df["Engines"].value_counts().sort_index().to_string())

Engines
0.36L Inline-2                                     1
0.66L Inline-3                                     1
0.7L 3-Cylinder                                    5
1.0L EcoBoost / 1.5L                               1
1.0L EcoBoost / 1.5L / 2.0L                        1
1.0L I3 Turbo                                      2
1.0L I3 Turbo / 1.5L I4 Turbo                      2
1.0L Inline-2 (Wankel)                             1
1.0L Turbo I3                                      1
1.0L Turbo I3 / 1.5L Turbo I4                      1
1.0L Turbo I3 / 1.6L Diesel                        1
1.0L Turbo Inline-3 / 2.0L                         1
1.0L Turbo Inline-4                                1
1.0L Turbocharged Inline-3                         4
1.0L,INLINE-3                                      1
1.1L / 1.5L MIVEC                                  1
1.2L Diesel I3                                     3
1.2L Hybrid                                        1
1.2L I4 Gas                                        1
1.2L I4 Gas / 1.4L I4 Gas                          1
1.2L I4 Turbo / 2.0L I4 Turbo                      2
1.2L Inline-3                                      1
1.2L Inline-3 Hybrid                               1
1.2L Inline-4                                      1
1.2L MIVEC                                         5
1.2L MPFI Petrol                                   1
1.2L Petrol                                        2
1.2L Revotron 3-cylinder Petrol                    4
1.2L Revotron Bi-Fuel                              1
1.2L Revotron Petrol                               1
1.2L Revotron Petrol / 1.5L Diesel                 1
1.2L Rotary                                        1
1.2L Turbo Inline-3 Gasoline                       1
1.2L Turbo Petrol / 1.5L Diesel                    1
1.2L Turbocharged Inline-4                         1
1.2L Turbocharged Petrol                           1
1.2L,4-CYLINDER,INLINE-4(I4)                       3
1.3L Inline-2 (Wankel)                             3
1.3L Inline-4                                      3
1.3L Quadrajet Diesel / 1.2L Revotron Petrol       1
1.3L Quadrajet Diesel / 1.4L Petrol                1
1.3L Rotary                                        1
1.3L Rotary Twin-Turbo                             1
1.3L Turbo Hybrid Inline-4                         1
1.3L Turbo I4 Gasoline                             1
1.3L Turbo Inline-3 Gasoline                       1
1.3L Turbo PHEV                                    2
1.3L Turbocharged Inline-4                         1
1.3L Wankel + Electric                             2
1.3L Wankel Rotary Engine                          2
1.4L CR4 Diesel                                    3
1.4L CR4 Diesel / 1.4L Petrol                      1
1.4L I3 Gas / 1.2L Diesel I3                       1
1.4L I4 Diesel / 1.6L Diesel                       1
1.4L I4 Gas / 1.6L I4 Gas                          1
1.4L I4 Turbo                                      1
1.4L I4 Turbo + Electric Motor                     4
1.4L I4 Turbo / 2.0L Diesel I4                     1
1.4L Inline-4                                      1
1.4L Inline-4 Gasoline                             3
1.4L MPFI Petrol                                   1
1.4L Turbo Inline-4 Gasoline                       1
1.4L,4-CYLINDER,INLINE-4(I4)                       1
1.5L 4-Cylinder                                    1
1.5L EcoBoost / 2.0L EcoBoost                      1
1.5L EcoBoost / 2.0L Hybrid                        1
1.5L EcoBoost / 2.5L Hybrid                        1
1.5L Hybrid                                        1
1.5L I4 CNG                                        1
1.5L I4 Gas                                        1
1.5L I4 Turbo                                      1
1.5L I4 Turbo / 2.0L Diesel                        2
1.5L Inline-4                                      9
1.5L Inline-4 Diesel                               2
1.5L MIVEC                                         2
1.5L SkyActiv-G                                    1
1.5L Turbo                                         2
1.5L Turbo 4-cylinder                              3
1.5L Turbo Hybrid                                  2
1.5L Turbo I4                                      4
1.5L Turbo I4 / 2.0L Diesel I4                     1
1.5L Turbo I4 / Electric                           1
1.5L Turbo Inline-3                                3
1.5L Turbo Inline-4 Gasoline                       6
1.5L Turbocharged                                  1
1.5L Turbocharged I4 engine                        3
1.5L Turbocharged Inline-3                         1
1.5L,4-CYLINDER,INLINE(I4)                         1
1.5L,HYBRID                                        1
1.6L 4-Cylinder                                    4
1.6L 4-Cylinder Hybrid                             4
1.6L Diesel / 2.0L I4 Turbo                        1
1.6L Hybrid Turbocharged 4-Cylinder                4
1.6L I4 Gas / 1.9L I4 Diesel                       1
1.6L I4 Gas / Diesel                               1
1.6L Inline-2 (Wankel)                             1
1.6L Inline-4                                     19
1.6L MIVEC                                         1
1.6L MIVEC / 2.0L                                  1
1.6L PETROL                                        1
1.6L PETROL + PLUG IN HYBRID SYSTEM                1
1.6L Turbo GDI 4-cylinder                          1
1.6L Turbo Inline-4                                1
1.6L Turbocharged 4-Cylinder                       9
1.6L Turbocharged Rally Engine                     1
1.6L,TURBOCHARGED INLINE-3                         2
1.8L / 2.0L Hybrid                                 1
1.8L I4 Gas                                        2
1.8L Inline-4                                     13
1.8L MIVEC                                         2
1.8L Rotary                                        1
1.8L Turbo Inline-4                                1
1.8L,HYBRID                                        1
12.8L I6 Turbo Diesel                              4
13.0L I6 Turbo Diesel                              2
16.1L I6 Turbo Diesel                              1
2.0L 4-Cylinder                                   11
2.0L Diesel / 2.2L Diesel                          1
2.0L Diesel I4                                     8
2.0L EcoBoost / 2.7L V6                            1
2.0L Gas / 2.0L Hybrid                             1
2.0L HYBRID                                        1
2.0L I4 Turbo                                     15
2.0L I4 Turbo / 3.6L V6 Gas                        1
2.0L I4 Turbo Diesel                               1
2.0L Inline-4                                     20
2.0L Inline-4 Hybrid                               1
2.0L Inline-6                                      1
2.0L Kryotec Turbocharged Diesel                   2
2.0L MIVEC                                         7
2.0L SkyActiv-G                                    5
2.0L Turbo 4-cylinder                              1
2.0L Turbo Diesel I4                               3
2.0L Turbo Flat-4                                  2
2.0L Turbo Gasoline                                1
2.0L Turbo I4                                     14
2.0L Turbo I4 Gasoline                             1
2.0L Turbo Inline-4                                9
2.0L Turbo Inline-4 Gasoline                       8
2.0L Turbo PHEV                                    2
2.0L Turbocharged                                  1
2.0L Turbocharged Flat-4                           1
2.0L Twin-Rotor Turbo                              1
2.0L VC-Turbo Inline-4                             1
2.0L,4-CYLINDER,INLINE-4(I4)                       2
2.0L,4-CYLINDER,WITH HYBRID SYSTEM                 1
2.0L,INLINE-4                                      1
2.2L Dicor Diesel                                  2
2.2L Diesel                                        1
2.2L Diesel Turbo                                  1
2.2L Varicor Diesel                                1
2.2L,4-CYLINDER,INLINE-4(I4)                       2
2.3L EcoBoost / 2.7L V6                            1
2.3L EcoBoost / 3.0L V6                            1
2.3L Inline-4 Diesel                               2
2.3L Miller Cycle V6                               1
2.3L Turbo Inline-4                                1
2.3L Turbo Inline-4 / 2.7L V6                      1
2.3L Turbocharged                                  1
2.4L 4-Cylinder                                    1
2.4L Diesel Turbo                                  7
2.4L Hybrid                                        1
2.4L I4 Tigershark Gasoline                        1
2.4L Inline-4                                      3
2.4L Inline-6                                      2
2.4L MIVEC                                         1
2.4L PHEV                                          1
2.4L Petrol                                        1
2.4L Turbo I4 (i-FORCE MAX Hybrid)                 1
2.5L 4-Cylinder                                    7
2.5L Diesel                                        1
2.5L Hybrid / 2.0L EcoBoost                        1
2.5L Hybrid / Plug-in Hybrid                       1
2.5L Hybrid I4                                     1
2.5L Hybrid Turbocharged 4-Cylinder                1
2.5L I4 engine                                     2
2.5L Inline-4                                      6
2.5L Inline-4 + Electric                           1
2.5L Inline-4 Diesel                               3
2.5L Inline-4 Gasoline                             1
2.5L Inline-4 Hybrid                               1
2.5L SkyActiv-G                                    4
2.5L Turbo Diese                                   1
2.5L Turbocharged                                  3
2.5L Turbocharged 4-Cylinder                       3
2.5L Turbocharged Flat-4                           1
2.5L Turbocharged Inline-4                         1
2.5L V6                                            6
2.5L,INLINE-4,HYBRID,OR 3.5L,V6                    1
2.6L Inline-4                                      1
2.6L Twin-Turbo Inline-6                           1
2.6L Wankel Rotary Engine                          1
2.7L Inline-4 Diesel                               1
2.7L Turbo 4-cylinder                              4
2.7L Turbo Diesel                                  1
2.7L Turbo Inline-4 Gasoline                       3
2.7L Turbo engine                                  1
2.7L Twin-Turbo V6                                 1
2.8L Inline-6                                      1
2.8L Inline-6 Diesel                               1
2.8L Turbo Diesel I4                               1
2.8L,TURBO,DIESEL                                  3
2.9L Twin-Turbo V6                                 7
2.9L Twin-Turbo V6 + Electric Motor                2
2.9L V6 + Electric Motor                           2
2.9L V6 Twin Turbo                                 8
2.9L VR6                                           1
3.0L CR4 Diesel                                    1
3.0L Diesel                                        1
3.0L Diesel Hybrid                                 1
3.0L Flat-6 Twin Turbo                             1
3.0L Inline-4                                      1
3.0L Inline-4 Diesel                               2
3.0L Inline-6                                      1
3.0L Turbo Diesel V6                               1
3.0L Turbocharged V6                               2
3.0L Twin-Turbo Flat-6                            15
3.0L Twin-Turbo V6                                 8
3.0L Twin-Turbo V6 Gasoline                        1
3.0L Twin-Turbo V6 Hybrid                          1
3.0L V6                                            8
3.0L V6 + Electric Motor                           2
3.0L V6 Diesel / 6.0L W12 Gas                      1
3.0L V6 Turbo                                      4
3.0L V6 Turbo Diesel                               2
3.0L V6 Turbo Diesel / 4.0L V8                     1
3.0L V6 Turbo Diesel / Gasoline                    1
3.0L V6 Twin-Turbo                                 2
3.2L Diesel Turbo                                  4
3.2L Turbo Diesel                                  1
3.2L V6 Pentastar Gasoline                         1
3.2L VR6                                           1
3.3L Inline-6 Turbo                                1
3.3L Turbocharged V6                               1
3.3L V6                                            3
3.3L V6 + Electric                                 1
3.3L V6 / 5.0L V8 / 3.5L EcoBoost                  1
3.3L,V6,TWIN TURBO DIESEL                          1
3.5L EcoBoost / 5.4L V8                            1
3.5L Twin-Turbo V6                                 2
3.5L Twin-Turbo V8                                 1
3.5L V6                                           11
3.5L V6 / 2.0L EcoBoost                            1
3.5L,V6,HYBRID TWIN-TURBO                          1
3.5L,V6,PLUG IN HYBRID                             1
3.6L Twin-Turbo V6 Gasoline                        1
3.6L V6 Gasoline                                  12
3.6L V6 Pentastar Gasoline                         5
3.6L V6 engine                                     7
3.7L V6                                            3
3.8L Twin-Turbo Flat-6                             7
3.8L Twin-Turbo V6                                 5
3.8L V6                                            9
4.0L Naturally Aspirated Flat-6                   10
4.0L Twin-Turbo V8                                 5
4.0L Twin-Turbo V8 + Electric Motor                3
4.0L V6                                            3
4.0L V8 + Electric Motor                           2
4.0L V8 Turbo Diesel                               2
4.0L V8 Twin Turbo                                 4
4.0L,DIESEL                                        1
4.1L V8                                            1
4.2L Inline-6                                      1
4.2L Naturally Aspirated Flat-6                    1
4.3L V6 Gasoline                                   2
4.3L V6 engine                                     1
4.5L V8                                            3
4.8L Inline-6                                      2
5.0L V8                                            2
5.1L I4 Turbo Diesel                               1
5.3L V8 Gasoline                                  16
5.3L V8 engine                                     6
5.6L V8                                           17
5.7L V8 Gasoline                                   1
5.7L V8 Gasoline with eTorque                      1
6.2L Supercharged V8 Gasoline                      3
6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel              1
6.2L V8 Gasoline                                  15
6.2L V8 engine                                     6
6.4L V8 Gasoline                                   1
6.4L V8 HEMI Gasoline                              1
6.6L V8 Diesel                                     6
6.6L V8 Gasoline                                   1
6.6L V8 engine                                     6
6.7L Turbo-Diesel / 7.3L V8                        1
624cc MPFI                                         1
657cc Turbocharged Inline-3                        1
660cc Inline-3                                     4
7.5L Diesel                                        1
7.7L I6 Turbo Diesel                               1
8.0L Quad-Turbo W16                               10
BOXER-4                                            2
Diesel I4                                          3
Dual Electric Motors                              23
Dual Electric Motors (AWD)                         3
Dual-Motor Electric                                2
ELECTRIC                                           2
ELECTRIC                                           1
ELECTRIC MOTOR                                     5
EcoBlue Turbo Diesel                               3
Electric                                          15
Electric (Dual Motor)                              5
Electric AWD                                       1
Electric Motor                                    20
Electric motors with advanced AWD                  1
Electric motors with up to 11,500 lb-ft torque     5
HYBRID                                             1
HYDROGEN FUEL CELL,ELECTRIC MOTOR                  1
Hybrid I4                                          7
Hybrid I4 + Electric Motor                         4
Hybrid I4+ Electric Motor                          1
I3                                                12
I4                                                64
I4 + ELECTRIC                                      3
I4 Hybrid                                          2
I4 Petrol                                         12
I4 Petrol + Electric Motor                         1
I4 Petrol / V6 Petrol                              9
I4 Turbo Diesel                                    1
I4 Turbocharged                                    3
I6                                                 9
Inline-4                                          38
Inline-4 Gasoline Engine                           1
Inline-4 Hybrid                                    1
Inline-4 Turbocharged                              1
Naturally Aspirated V6                             1
Naturally Aspirated V8                             1
Permanent Magnet Synchronous                       5
Plug-in Hybrid (0.8L I2 Diesel)                    1
Plug-in Hybrid (1.4L I4 Turbo)                     1
Plug-in Hybrid / Diesel I4                         1
Plug-in Hybrid V6                                  1
Quad Electric Motors                               1
Rotary SkyActiv-R                                  1
Single Electric Motor                              6
Single Electric Motor (RWD)                        2
Supercharged V8                                    1
Tri Electric Motors                                3
Turbocharged I4                                    1
Turbocharged Inline-3                              1
Turbocharged Inline-4                              2
Turbocharged V6                                    5
Turbocharged V8 Diesel                             2
Twin-Turbo V6 Hybrid                               4
V10                                               11
V12                                               51
V6                                                39
V6 / V8 Petrol                                     1
V6 EcoBoost                                        1
V6 Hybrid                                          2
V6 Hybrid + Electric Motor                         1
V6 Petrol                                          4
V6 Turbocharged                                    1
V8                                                34
V8 Gasoline Engine                                 2
V8 Petrol                                          8

### `Engines column` column
The next value it is duplicaded:
- ELECTRIC

In [11]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

## CC/Battery Capacity

In [12]:
print(df["CC/Battery Capacity"].value_counts().sort_index().to_string())

CC/Battery Capacity
-                                                    2
1,000 - 1,500 cc                                     1
1,000 - 2,000 cc                                     2
1,000 cc                                             2
1,100 - 1,500 cc                                     1
1,197 cc                                             3
1,199 cc                                            10
1,200 cc                                             9
1,298 cc                                             1
1,300 cc                                             4
1,308 cc                                             7
1,396 cc                                             1
1,462 cc                                             1
1,490 cc                                             4
1,496 cc                                             6
1,497 cc                                             3
1,498 cc                                             3
1,499 cc                                            14
1,500 - 2,000 cc                                     2
1,500 - 2,500 cc                                     1
1,500 cc                                            16
1,500 cc (I4)                                        3
1,560 cc                                             2
1,588 cc                                             1
1,590 cc                                             1
1,591 cc                                             1
1,598 cc                                            16
1,598 cc (petrol) + Electric Motor                  10
1,598 cc / 13.8 kwh                                  1
1,599 cc (Petrol) + Electric Motor                   1
1,599 cc (petrol) + Electric Motor                   1
1,600 - 2,000 cc                                     1
1,600 cc                                             8
1,600 cc / 1.49 kwh                                  1
1,600 cc / 13.8 kwh                                  1
1,618 cc                                             2
1,798 cc                                             5
1,800 cc                                             7
1,969 cc                                             3
1,984 cc                                             6
1,986 cc                                             3
1,987 cc                                             2
1,991 cc                                             6
1,995 cc                                             5
1,996 cc                                             2
1,997 cc                                             3
1,998 cc                                            19
1,999 cc                                             1
1.24 kwh                                             1
1.56 kwh                                             1
100 kWh                                              8
11.4 kWh                                             2
11.6 kwh                                             1
1192 cc                                              1
1193 cc                                              1
1197 cc                                              1
1197 cc / 1984 cc                                    2
1198 cc                                              3
1198 cc / 1390 cc                                    1
1199 cc                                             10
1199 cc / 1497 cc                                    2
1200 cc                                              1
1248 cc / 1199 cc                                    1
1248 cc / 1368 cc                                    1
12800 cc                                             4
1300 cc                                              2
13000 cc                                             2
1332 cc                                              2
1390 cc / 1199 cc                                    1
1390 cc / 1598 cc                                    2
1395 cc                                              4
1395 cc + Battery                                    1
1395 cc + Electric Motor                             1
1395 cc / 1968 cc                                    2
1396 cc                                              5
1397 cc                                              1
1400 cc                                              4
1461 cc                                              2
1497 cc                                              6
1498 cc                                             10
1498 cc / 1968 cc                                    3
1498 cc / 40 - 58 kWh                                1
1500 cc                                              9
1591 cc                                             22
1595 cc                                              2
1597 cc                                              3
1598 cc                                              8
1598 cc / 1896 cc                                    1
1598 cc / 1984 cc                                    1
16 kWh battery                                       2
16100 cc                                             1
17.3 kWh                                             2
17.9 kWh Battery                                     4
1769 cc                                              1
1770 cc                                              1
1781 cc                                              2
1796 cc                                              1
1798 / 1987 cc + batt                                1
1798 cc                                              3
1809 cc                                              1
1838 cc                                              1
1839 cc                                              1
1956 cc                                              2
1968 cc                                             12
1984 cc                                             31
1984 cc / 3597 cc                                    1
1987 cc / Hybrid batt                                1
1988 cc                                              3
1991 cc                                              1
1997 cc                                              4
1998 cc                                             15
1998 cc (I4)                                         1
1999 cc                                             10
1999 cc (I4)                                        11
1999 cc (I4) + Electric                              1
1999 cc (I4) / 2995 cc (V6)                          9
2,000 - 2,200 cc                                     1
2,000 - 2,700 cc                                     1
2,000 - 3,500 cc                                     1
2,000 cc                                            31
2,179 cc                                             2
2,200 cc                                             4
2,300 - 2,700 cc                                     2
2,300 - 3,000 cc                                     1
2,300 cc                                             3
2,387 cc                                             1
2,400 cc                                            15
2,400 cc (I4)                                        1
2,400 cc / 20 kWh battery                            1
2,480 cc                                            11
2,488 cc                                             4
2,494 cc                                             4
2,500 - 2,000 cc                                     1
2,500 cc                                            25
2,500 cc (petrol) + Electric Motor                   2
2,600 cc                                             1
2,620 cc                                             1
2,694 cc                                             1
2,700 cc                                             2
2,713 cc                                             1
2,755 cc                                             3
2,993 cc                                             5
2,995 cc                                             7
2,996 cc                                             8
2,998 cc                                             3
200 kWh                                              8
2000 cc                                             11
212 kWh                                              2
2179 cc                                              3
2298 cc                                              2
2389 cc                                              2
2393 cc                                              2
2393 cc + Battery                                    1
24 kWh                                               2
2400 cc                                              1
2438 cc                                              1
2487 cc                                              1
2487 cc + batt                                       1
2488 cc                                              3
2497 cc                                              1
2498 cc                                              4
2500 cc                                              5
2568 cc                                              1
26 kWh                                               1
2663 cc                                              1
2664 cc                                              1
2700 cc                                              7
2753 cc                                              1
2800 cc                                              1
2825 cc                                              1
2861 cc                                              1
2894 cc                                             17
2953 cc                                              1
2956 cc                                              1
2960 cc                                              6
2967 cc                                              4
2967 cc / 3956 cc                                    1
2967 cc / 5998 cc                                    1
2981 cc                                             16
2995 cc                                              7
2995 cc (V6)                                         5
2997 cc                                              7
2999 cc                                              1
3,000 cc                                            14
3,000 cc (petrol) + Electric Motor                   1
3,200 cc                                             5
3,300 - 5,000 cc                                     1
3,300 cc                                             4
3,346 cc                                             1
3,445 cc                                             1
3,456 cc                                             5
3,471 cc                                             1
3,493 cc                                             3
3,493 cc (V6)                                        1
3,498 cc                                             2
3,500 - 5,400 cc                                     1
3,500 cc                                            13
3,500 cc (V6)                                        5
3,564 cc                                             7
3,696 cc                                             1
3,799 cc                                             2
3,800 cc                                             3
3,900 cc                                             6
3,956 cc                                             2
3,982 cc                                             5
3,993 cc                                             4
3,994 cc                                             1
3,996 cc                                             7
3,998 cc                                             1
30.2 kWh                                             1
3000 cc                                              2
3189 cc                                              1
32.3 kWh                                             2
3200 cc                                              1
3275 cc                                              1
3300 cc                                              1
3495 cc                                              1
3498 cc                                              6
35.5 kWh battery                                     1
35.8 kWh                                             1
3500 cc                                              5
360 cc                                               1
3600 cc                                             18
3696 cc                                              3
3745 cc                                              7
3778 cc                                              6
3799 cc                                              5
39.2 kwh                                             1
3954 cc                                              3
3956 cc                                              1
3990 cc                                              1
3995 cc                                              3
3996 cc                                             20
4,009 cc                                             1
4,300 cc                                             1
4,395 cc                                             3
4,935 cc                                             2
40.5 kWh                                             1
4130 cc                                              1
4169 cc                                              1
4194 cc                                              1
4300 cc                                              2
4494 cc                                              3
4750 cc                                              2
5,000 cc                                             2
5,200 cc                                             2
5,204 cc                                            14
5,327 cc                                             6
5,598 cc                                             1
5,663 cc                                             3
5,935 cc                                             3
5,980 cc                                             1
50 kWh                                               3
5000 cc (V8)                                         8
5026 cc                                              1
5100 cc                                              1
53.6 kwh(Standard Range) / 77.4 kwh(Long Range)      1
5300 cc                                             16
5552 cc                                             17
5700 cc                                              2
58 - 77 kWh                                          1
58 kWh                                               1
6,162 cc                                             6
6,200 - 7,300 cc                                     1
6,496 cc                                             2
6,498 cc                                            11
6,592 cc                                            15
6,600 cc                                             6
6,700 - 7,300 cc                                     1
6,700 cc                                             2
6,749 cc                                            14
60 kWh                                               1
6200 cc                                             18
624 cc                                               1
64.8 kwh (Base Model),72.8 kwh (Higher End Model     1
6400 cc                                              2
6496 cc                                              1
65 KWH                                               1
657 cc                                               2
659 cc                                               1
66 kWh                                               4
660 cc                                               8
6600 cc                                              7
6749 cc                                              1
7,300 cc                                             1
7,500 cc                                             1
72.6 KWH                                             1
75 KWH                                               1
75 kWh                                               1
77 kWh                                              10
77.4 kWh                                             6
7700 cc                                              1
79.2 kWh                                             5
7993 cc                                             10
800 cc + Electric Motor                              1
82 kWh                                               2
87 kWh                                               6
89 kWh (Electric)                                    1
90 kWh (Battery)                                     5
93.4 kWh                                             8
95 kWh                                               1
95 kwh                                               2
987 cc                                               1
998 cc                                               1
999 cc                                               7
999 cc / 1498 cc                                     3
999 cc / 1598 cc                                     1
Battery (68-98 kWh)                                  1
Battery (98 kWh)                                     1
HYBRID(2,494 cc),V6(3,456 cc)                        1
~50 kWh (Estimate)                                   1

### The `CC/Battery Capacity` column has highly inconsistent formatting: 
Single values (`1,500 cc`), ranges (`1,000 - 1,500 cc`), combined combustion + electric powertrains (`1,598 cc (petrol) + Electric Motor`), mixed units within the same field (`1,600 cc / 13.8 kWh`) and null values expressed as `-`.
Before this can be used as a numeric feature, it will need to be standardized.

## HorsePower column

In [13]:
values_set = repeated_values(df["HorsePower"])
values_set

{'100 hp',
 '102 hp',
 '105 hp',
 '109 hp',
 '110 hp',
 '114 hp',
 '115 hp',
 '118 hp',
 '120 hp',
 '125 hp',
 '129 hp',
 '130 hp',
 '134 hp',
 '135 hp',
 '137 hp',
 '138 hp',
 '140 hp',
 '145 hp',
 '150 hp',
 '151 hp',
 '155 hp',
 '158 hp',
 '170 hp',
 '175 hp',
 '187 hp',
 '190 hp',
 '200 hp',
 '201 hp',
 '204 hp',
 '204 hp ',
 '205 hp',
 '210 hp',
 '247 hp',
 '250 hp',
 '255 hp',
 '261 hp',
 '268 hp',
 '270 hp',
 '276 hp',
 '280 hp',
 '284 hp',
 '300 hp',
 '325 hp',
 '332 hp',
 '335 hp',
 '340 hp',
 '350 hp',
 '375 hp',
 '379 hp',
 '400 hp',
 '420 hp',
 '434 hp',
 '440 hp',
 '453 hp',
 '455 hp',
 '473 hp',
 '48 hp',
 '500 hp',
 '550 hp',
 '600 hp',
 '670 hp',
 '690 hp',
 '85 hp'}

In [14]:
print(df["HorsePower"].value_counts().sort_index().to_string())

HorsePower
1,020 hp            2
1,288 hp            1
100 - 150 hp        1
100 HP              3
100 hp              7
1000 hp             1
102 - 150 hp        1
102 - 177 hp        1
102 - 204 hp        1
102 HP              1
102 hp              1
103 hp              1
104 HP              1
105 - 110 hp        1
105 - 210 hp        3
105 HP              2
105 hp              4
106 hp              1
108 hp              2
109 HP              1
109 hp              2
110 - 320 hp        1
110 HP              3
110 hp              6
113 hp              1
114 HP              1
114 hp              1
115 - 150 hp        2
115 - 300 hp        1
115 HP              3
115 hp              6
116 hp              4
1160 hp             1
117 - 148 hp        1
117 HP              1
118 HP              1
118 hp              1
118 hp / 110 hp     1
119 hp              1
120 - 240 hp        1
120 - 300 hp        1
120 HP              2
120 hp              9
121 hp              2
122 - 150 hp        1
122 HP              3
123 - 166 hp        1
123 hp              1
125 - 280 hp        1
125 HP              3
125 hp              1
126 HP              1
127 HP              1
129 HP              1
129 hp              1
130 - 150 hp        2
130 HP              2
130 hp             18
131 HP              1
133 HP              1
134 HP              2
134 hp              2
135 HP              1
135 hp              6
136 hp             13
137 HP              1
137 hp              2
138 HP              1
138 hp              4
139 hp              7
140 HP              5
140 hp              8
140  198 hp        1
141 HP              2
143 hp              4
144 hp              1
145 HP              1
145 hp              3
146 hp              3
147 - 150 hp        1
147 - 200 hp        1
147 hp             12
148 hp              5
149 hp              1
150 - 184 hp        4
150 - 200 hp        1
150 - 204 hp        1
150 - 218 hp        1
150 - 220 hp        1
150 - 228 hp        1
150 - 230 hp        1
150 - 240 hp        1
150 - 280 hp        3
150 - 320 hp        1
150 HP              3
150 hp              7
1500 hp             6
151 HP              2
151 hp              1
152 hp              3
154 hp              2
155 HP              1
155 hp              3
156 HP              1
158 HP              2
158 hp              3
159 hp              1
160 - 250 hp        1
160 hp              8
1600 hp             3
161 hp              1
162 hp              1
163 - 258 hp        1
163 hp              1
164 hp              1
165 hp              3
168 hp              3
169 hp              1
169  196 hp        1
170 HP              1
170 hp             12
174 - 299 hp        1
174 hp              1
175 HP              1
175 hp              7
177 hp              1
178 hp              3
179 HP              1
180 hp             15
181 - 200 hp        1
181 - 250 hp        1
181 hp             16
184 - 230 hp        1
184 hp              2
1850 hp             1
186 hp              2
187 HP              1
187 hp             15
188 hp              2
189 hp              4
190 - 230 hp        1
190 - 240 hp        1
190 - 280 hp        1
190 - 320 hp        1
190 HP              3
190 hp              4
191 - 250 hp        1
191 hp              3
192 hp              2
193 hp              1
200 - 280 hp        1
200 - 365 hp        1
200 HP              2
200 hp             21
201 - 302 hp        1
201 HP              3
201 hp              9
203 hp              1
204 - 258 hp        1
204 HP              2
204 hp             10
204 hp              1
205 HP              1
205 hp              2
206 hp              1
207 hp              1
208 hp              1
210 HP              2
210 hp              4
215 hp              1
218 hp              1
219 hp              1
219  302 hp        1
220 hp              2
221 hp              1
224 hp              3
225 hp              8
227 hp              5
228 hp              4
230 HP              1
231 - 340 hp        1
231 - 500 hp        1
235 - 276 hp        1
235 hp              2
236 hp              1
237 hp              3
240 - 450 hp        1
240 hp              9
241 hp              1
244 hp              1
245 hp              3
246 hp              1
247 HP              1
247 hp              4
248 hp              7
2488 cc             1
250 - 335 hp        1
250 HP              3
250 hp              9
250 hp / 340 hp     1
253 hp              1
255 HP              2
255 hp              6
256 hp              1
26 hp               1
260 HP              2
261 HP              4
261 hp              4
262 hp              1
265 hp              3
266 hp              1
268 HP              1
268 hp              1
270 - 325 hp        1
270 HP              1
270 hp              3
271 hp              1
272 hp              6
275 - 310 hp        1
275 hp              2
276 HP              1
276 hp              1
277 hp              1
278 hp              2
280 HP              5
280 hp              6
281 hp              1
282 hp              1
283 hp              1
284 HP              2
284 hp              1
285 hp              7
287 hp              1
290 - 450 hp        1
290 hp             15
290-480 hp          1
291 hp              9
293 hp              2
295 hp              2
296 hp              1
299 hp              2
300 - 400 hp        1
300 HP              4
300 hp             20
301 hp              2
302 hp              1
305 hp              1
306 hp              1
308 hp              6
310 - 340 hp        1
310 hp             22
315 hp              2
318 hp              1
320 hp              4
321 hp              3
325 HP              1
325 hp              4
326 hp              1
328 HP              1
330 HP              4
332 HP              1
332 hp              1
335 HP              2
335 hp              7
34 - 60 hp          1
340 HP              1
340 hp             10
344 hp              1
346 hp              1
349 hp              3
350 HP              1
350 hp              2
355 hp             23
357 hp              1
360 hp              5
362 hp              3
365 hp              1
369 hp              1
37 hp               1
375 - 400 hp        1
375 HP              2
375 hp              5
379 HP              1
379 hp              6
380 hp              2
381 hp              3
382 hp              4
384 hp              1
385 - 475 hp        1
389 HP              6
390 HP              1
392 hp              2
394 hp              1
398 hp              1
400 HP             16
400 hp             12
400 hp (est.)       1
401 hp              9
402 hp              5
406 hp              1
414 hp              2
416 hp              1
420 HP              1
420 hp             17
421 hp              1
428 HP              5
429 hp              3
434 HP              2
434 hp              2
437 hp              1
440 HP              1
440 hp              1
443 hp              4
444 hp              1
445 hp              4
450 - 475 hp        1
450 hp              6
452 hp              1
453 HP              1
453 hp              1
455 HP              2
455 hp              2
457 hp              1
460 hp              2
462 hp              2
469 hp              1
470 hp              1
471 hp              1
472 hp              1
473 HP              1
473 hp              7
475 hp              2
48 HP               1
48 hp               1
493 hp              2
495 hp              2
496 hp              1
500 HP              1
500 hp              6
502 hp              2
503 hp              4
509 hp              1
510 hp              2
515 hp              1
518 hp              1
52 hp               2
522 hp              1
523 hp              4
525 hp              1
526 hp              1
537 hp              2
54 hp               1
540 hp              2
541 HP              1
542 hp              1
55 - 75 hp          1
550 HP              1
550 hp              7
560 hp              1
563 hp             20
565 HP              1
570 hp              1
572 hp              3
575 hp              1
577 hp              1
580 hp              2
590 hp              3
591 hp              5
592 hp              1
60 - 75 hp          1
60 hp               1
600 HP              3
600 hp              4
602 hp              1
603 hp              3
607 hp              1
61 hp               1
610 hp              4
612 hp              3
620 HP              1
623 hp              3
624 hp              6
625 hp              2
627 hp              1
63 hp               3
630 hp              2
631 hp              1
64 hp               4
640 hp              8
641 hp              3
65 hp               1
650 hp              1
656 hp              1
66 hp               1
660 hp              1
668 hp              1
67 HP               1
670 HP              1
670 hp              4
671 hp              1
68 hp               1
682 hp              1
690 HP              1
690 hp              1
70 - 85 hp          1
70 hp               4
70 hp / 85 hp       1
70-85 hp            1
700 hp              3
71 hp               1
710 hp              3
715 hp              1
720 HP              1
728 hp              1
74 hp               3
740 hp              2
75 - 105 hp         1
75 - 150 hp         1
75 - 95 hp          2
75 hp               3
75 hp / 90 hp       2
750 hp              4
751 hp              1
759 hp              3
76 HP               1
760 hp              1
769 hp              3
78 hp               5
789 hp              2
79 HP               1
80 - 200 hp         1
800 hp              1
819 hp              1
82 - 115 hp         1
82 hp               3
83 hp               3
836 hp              1
85 - 105 hp         1
85 - 200 hp         1
85 HP               2
85 hp               4
86 hp               6
86 hp / 89 hp       1
87 hp               1
92 hp               1
94 HP               1
95 - 150 hp         2
95 hp               4
96 HP               2
963 hp              1
98 hp               4
99 hp               1
Up to 1,000 hp      2
Up to 754 hp        1
Up to 830 hp        3
~170 hp             1

### The `HorsePower` column is also highly inconsistent in format.
It mixes single values (`130 hp`, `310 hp`), ranges (`100 - 150 hp`,
`290-480 hp`, note the inconsistent spacing around the dash), inconsistent
casing (`hp` vs `HP`), dual values likely for different trims/engines
(`118 hp / 110 hp`), approximate values (`~170 hp`), qualified estimates
(`400 hp (est.)`), open-ended bounds (`Up to 1,000 hp`), and at least one
likely data-entry error (`2488 cc`, which is a displacement value mixed
into the horsepower column). Before this can be used as a numeric feature,
it will need standardization: strip units and symbols, normalize casing,
resolve ranges/dual values (e.g., using the midpoint or minimum), and
review outliers or misplaced values like the `cc` entry.

## Total spped column

In [15]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [16]:
print(df["Total Speed"].value_counts().sort_index().to_string())

Total Speed
100 km/h             2
105 km/h             1
110 km/h             4
120 km/h            15
125 km/h             1
130 km/h            15
138 km/h             1
140 km/h            16
145 km/h             9
148 km/h             1
150 km/h            10
155 km/h             5
160 km/h            44
162 km/h             1
165 km/h            12
168 km/h             1
170 km/h            47
175 km/h            24
177 km/h             7
180 km/h           129
183 km/h             1
185 km/h            18
186 km/h             2
187 km/h             1
190 km/h            92
191 km/h             2
193 km/h             1
195 km/h             8
196 km/h             1
200 km/h           139
201 km/h             1
204 km/h             1
205 km/h             9
209 km/h             5
210 km/h            85
211 km/h             1
213 km/h             5
215 km/h             8
216 km/h             2
217 km/h             4
220 km/h            48
221 km/h             1
222 km/h             1
225 km/h            12
226 km/h             2
230 km/h            24
232 km/h             3
233 km/h             2
235 km/h            10
237 km/h             1
238 km/h             1
240 km/h            39
242 km/h             1
245 km/h             4
246 km/h             1
250 km/h           145
253 km/h             1
259 km/h             2
260 km/h             6
261 km/h             1
262 km/h             1
263 km/h             1
265 km/h             4
270 km/h            10
272 km/h             3
275 km/h             3
280 km/h             7
283 km/h             1
285 km/h             5
286 km/h             1
289 km/h             4
290 km/h             8
291 km/h             1
293 km/h             6
295 km/h             4
296 km/h             3
300 km/h             8
300 km/h (est.)      1
301 km/h             1
302 km/h             1
304 km/h             1
305 km/h            11
306 km/h             2
307 km/h             4
308 km/h             1
310 km/h             1
311 km/h             2
312 km/h             2
313 km/h             1
314 km/h             2
315 km/h             8
318 km/h             5
320 km/h            12
322 km/h             2
324 km/h             1
325 km/h             9
328 km/h             1
330 km/h             7
340 km/h             7
341 km/h             1
348 km/h             1
350 km/h             8
354 km/h             1
355 km/h             3
356 km/h             1
362 km/h             1
380 km/h             2
402 km/h             2
420 km/h             5
490 km/h             1
500 km/h             1
80 km/h              1
85 km/h              1
90 km/h              1

### The `Total Speed` column needs to standardized.
It has to be remove `km/h` unit from all the entries. Also, one entry contains the indicator `(est.)`, which needs to be removed.

## Performance(0 - 100 )KM/H column

In [17]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [18]:
print(df["Performance(0 - 100 )KM/H"].value_counts().sort_index().to_string())

Performance(0 - 100 )KM/H
 6.1 sec               1
1.9 sec                1
10 sec                 2
10. 5 sec              1
10.0 sec              19
10.1 sec               1
10.2 sec              14
10.3 sec               5
10.4 sec               3
10.5 sec              38
10.6 sec               3
10.7 sec               4
10.8 sec               4
10.9 sec               4
11 sec                 3
11.0 sec              18
11.2 sec               6
11.5 sec              11
11.7 sec               1
11.9 sec               2
12 sec                 3
12.0 sec              17
12.2 sec               6
12.3 sec               1
12.4 sec               1
12.5 sec              13
12.8 sec               1
12.9 sec               2
13 sec                 3
13.0 sec               9
13.5 sec               6
13.7 sec               1
13.8 sec               1
14 sec                 1
14.0 sec               8
14.3 sec               1
14.5 sec               3
14.8 sec               2
15 sec                 3
15.0 sec              11
15.5 sec               4
16 sec                 3
16.0 sec               4
16.5 sec               2
17 sec                 2
17.0 sec               1
17.5 sec               1
17.6 sec               1
18.0 sec               3
18.5 sec               1
2.1 sec                1
2.2 sec                1
2.3 sec                1
2.4 sec                5
2.5 sec                7
2.6                    1
2.6 sec                1
2.7                    1
2.7 sec                1
2.8                    1
2.8 sec               11
2.9 sec               20
20.0 sec               1
22.0 sec               1
23.0 sec               1
29 sec                 1
3.0 sec               13
3.1 sec                6
3.2                    4
3.2 sec                7
3.3                    1
3.3 sec                8
3.4                    3
3.4 sec               10
3.5                    2
3.5 sec                9
3.5 sec (GT Model)     1
3.6                    2
3.6 sec               11
3.7                    1
3.7 sec                4
3.8                    2
3.8 sec                3
3.9                    1
3.9 sec               11
35.0 sec               1
4                      1
4.0 sec                7
4.1                    3
4.1 sec                7
4.2                    2
4.2 sec                7
4.3                    2
4.3 sec                7
4.4                    3
4.4 sec               10
4.5                    1
4.5 sec               20
4.6                    1
4.6 sec                2
4.7                    2
4.7 sec                7
4.8                    2
4.8 sec               14
4.9                    2
4.9 sec               10
5. 0 sec               1
5.0 - 6.5 sec          1
5.0 sec               12
5.1 sec               17
5.2 sec               12
5.3 sec                8
5.4                    2
5.4 sec               11
5.5                    1
5.5 sec               14
5.6                    2
5.6 sec               13
5.7 sec               16
5.8                    1
5.8 sec                8
5.9                    1
5.9 sec               12
6 sec                  1
6.0 - 7.0 sec          1
6.0 sec               31
6.0  8.1 sec          1
6.1 sec                7
6.2                    1
6.2 sec               11
6.3 sec                9
6.4                    1
6.4 sec                7
6.5                    1
6.5 - 7.0 sec          1
6.5 - 8.0 sec          1
6.5 sec               45
6.6 sec               16
6.7 sec               13
6.8 sec               20
6.9 sec               13
7.0 - 8.0 sec          1
7.0 sec               26
7.1  sec               1
7.1 sec                8
7.2 sec                8
7.2 sec / 5.4 sec      1
7.3                    1
7.3 sec               12
7.4 sec               13
7.5 sec               43
7.6 sec               12
7.7 sec                6
7.8 sec               15
7.9 sec                8
7.9  10.5 sec         1
8 sec                  1
8.0 sec               34
8.0  9.2 sec          1
8.1 sec                5
8.2 sec               12
8.3 sec                5
8.4 sec                9
8.5 sec               40
8.6 sec                8
8.7 sec                3
8.8 sec                7
8.9 sec                7
9 sec                  1
9.0 - 12.0 sec         1
9.0 sec               18
9.1 sec                1
9.2 sec                9
9.3 sec                6
9.4 sec                7
9.5 sec               31
9.6 sec                7
9.7 sec                2
9.8 sec                7
9.9 sec                1

### `Performance(0 - 100 )KM/H` column is inconsistent
In all entries needs to be removed any entra word like `sec` and `(GT Model)`. Also, it has to be removed any operations, ranges or special characteres `(9.0 - 12.0 sec, 7.2 sec / 5.4 sec, 8.0 ? 9.2 sec)`, so the column can be parse to float type

## Cars Prices column

In [19]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [20]:
print(df["Cars Prices"].value_counts().to_string())

Cars Prices
$35,000                    36
$30,000                    32
$50,000                    31
$55,000                    29
$25,000                    28
$45,000                    28
$40,000                    27
$28,000                    23
$60,000                    22
$70,000                    18
$20,000                    15
$18,000                    15
$85,000                    14
$32,000                    13
$22,000                    12
$20,000 - $25,000          12
$38,000                    11
$52,000                     9
$42,000                     9
$36,000                     9
$25,000 - $30,000           9
$30,000 - $35,000           9
$27,000                     8
$33,000                     8
$65,000                     8
$48,000                     7
$75,000                     7
$44,000                     7
$15,000                     7
$23,000                     7
$35,000 - $40,000           7
$18,000 - $22,000           7
$90,000                     6
$95,000                     6
$12,000 - $15,000           6
$10,000 - $12,000           6
$15,000 - $18,000           6
$53,000                     5
$62,000                     5
$46,000                     5
$58,000                     5
$39,000                     5
$37,000                     5
$29,000                     5
$31,000                     5
$12,000                     5
$47,000                     5
$80,000                     5
$110,000                    5
$1,100,000                  4
$49,000                     4
$26,000                     4
$22,500                     4
$24,000                     4
$19,000                     4
$14,000                     4
$14,500                     4
$18,500                     4
$105,000                    4
$120,000                    4
$100,000                    4
$40,000 - $45,000           4
$27,000 - $35,000           4
$45,000 - $50,000           4
$14,000 - $18,000           4
$220,000                    3
$63,000                     3
$78,000                     3
$18,400                     3
$170,000                    3
$28,500                     3
$113,300                    3
$222,000                    3
$23,500                     3
$3,300,000                  3
$157,000                    3
$25,000 - $28,000           3
$15,000 - $20,000           3
$15,000 - $17,000           3
$22,000 - $28,000           3
$4,500,000                  2
$280,000                    2
$350,000                    2
$240,000                    2
$113,000                    2
$142,000                    2
$287,000                    2
$421,000                    2
$545,000                    2
$258,000                    2
$573,000                    2
$330,000                    2
$360,000                    2
$500,000                    2
$116,000                    2
$104,000                    2
$109,000                    2
$54,000                     2
$102,000                    2
$200,000                    2
$114,000                    2
$69,000                     2
$43,000                     2
$68,000                     2
$57,000                     2
$34,000                     2
$41,000                     2
$38,400                     2
$26,400                     2
$41,400                     2
$33,400                     2
$43,400                     2
$15,400                     2
$20,400                     2
$10,400                     2
$56,000                     2
$20,500                     2
$150,000                    2
$15,500                     2
$77,000                     2
$51,000                     2
$16,000                     2
$42,500                     2
$17,500                     2
$185,000                    2
$10,000                     2
$92,000                     2
$130,000                    2
$190,000                    2
$86,700                     2
$65,500                     2
$98,300                     2
$72,200                     2
$11,000                     2
$25,500                     2
$65,895                     2
$56,995                     2
$41,500                     2
$45,500                     2
$28,795                     2
$43,500                     2
$34,500                     2
$64,100                     2
$43,900                     2
$108,700                    2
$82,000                     2
$96,550                     2
$35,500                     2
$35,000 - $45,000           2
$28,000 - $35,000           2
$23,000 - $26,000           2
$40,000 - $50,000           2
$28,000 - $30,000           2
$50,000 - $60,000           2
$20,000 - $23,000           2
$18,000 - $20,000           2
$22,000 - $26,000           2
$18,000 - $24,000           2
$8,000 - $10,000            2
$20,000 - $24,000           2
$460,000                    1
$12,000-$15,000             1
$161,000                    1
$253,290                    1
$499,000                    1
$193,440                    1
$311,000                    1
$210,000                    1
$230,000                    1
$1,700,000                  1
$53,900                     1
$3,200,000                  1
$316,000                    1
$208,000                    1
$189,000                    1
$294,000                    1
$1,300,000                  1
$2,800,000                  1
$518,000                    1
$274,000                    1
$261,000                    1
$493,000                    1
$211,000                    1
$445,000                    1
$308,000                    1
$242,000                    1
$263,000                    1
$327,000                    1
$273,000                    1
$603,000                    1
$253,000                    1
$342,000                    1
$332,000                    1
$325,000                    1
$370,000                    1
$390,000                    1
$450,000                    1
$340,000                    1
$380,000                    1
$320,000                    1
$99,000                     1
$71,000                     1
$133,000                    1
$76,000                     1
$83,000                     1
$146,000                    1
$108,000                    1
$398,000                    1
$381,000                    1
$475,000                    1
$335,000                    1
$349,000                    1
$495,000                    1
$355,000                    1
$369,000                    1
$418,000                    1
$401,000                    1
$515,000                    1
$375,000                    1
$389,000                    1
$439,000                    1
$194,000                    1
$101,000                    1
$96,000                     1
$86,000                     1
$64,000                     1
$59,000                     1
$165,000                    1
$81,000                     1
$32,500                     1
$29,400                     1
$26,500                     1
$26,350                     1
$26,700                     1
$27,100                     1
$37,400                     1
$39,900                     1
$52,400                     1
$44,150                     1
$40,400                     1
$49,400                     1
$24,400                     1
$12,400                     1
$16,400                     1
$11,400                     1
$14,400                     1
$31,100                     1
$36,995                     1
$58,500                     1
$25,390                     1
$49,500                     1
$40,799                     1
$19,950                     1
$41,450                     1
$30,500                     1
$28,505                     1
$21,995                     1
$39,735                     1
$59,995                     1
$31,965                     1
$44,640                     1
$16,700                     1
$41,820                     1
$58,950                     1
$70,600                     1
$13,000                     1
$24,960                     1
$42,820                     1
$65,300                     1
$45,790                     1
$41,750                     1
$175,000                    1
$98,000                     1
$61,750                     1
$67,000                     1
$600,000                    1
$1,000,000                  1
$88,000                     1
$180,000                    1
$115,000                    1
$131,300                    1
$106,500                    1
$121,300                    1
$197,200                    1
$230,400                    1
$161,100                    1
$241,300                    1
$103,800                    1
$150,900                    1
$132,750                    1
$97,700                     1
$63,400                     1
$75,400                     1
$100,200                    1
$141,700                    1
$69,600                     1
$90,300                     1
$92,300                     1
$101,400                    1
$200,200                    1
$128,900                    1
$136,900                    1
$175,200                    1
$290,000                    1
$70,400                     1
$82,900                     1
$91,000                     1
$94,300                     1
$182,150                    1
$79,000                     1
$167,800                    1
$111,200                    1
$85,500                     1
$182,900                    1
$34,395                     1
$46,595                     1
$38,195                     1
$50,995                     1
$94,800                     1
$139,400                    1
$90,500                     1
$136,700                    1
$106,100                    1
$129,900                    1
$137,000                    1
$157,300                    1
$184,100                    1
$207,000                    1
$223,800                    1
$145,300                    1
$135,500                    1
$293,200                    1
$245,000                    1
$750,000                    1
$191,300                    1
$233,000                    1
$8,200                      1
$11,300                     1
$11,800                     1
$9,200                      1
$4,000                      1
$6,200                      1
$5,000                      1
$9,400                      1
$8,700                      1
$6,500                      1
$79,295                     1
$8,300                      1
$9,000                      1
$7,000                      1
$7,200                      1
$82,295                     1
$10,500                     1
$16,500                     1
$88,490                     1
$108,490                    1
$40,240                     1
$53,240                     1
$98,490                     1
$113,490                    1
$47,490                     1
$50,490                     1
$69,900                     1
$35,195                     1
$42,100                     1
$41,530                     1
$43,530                     1
$37,695                     1
$31,590                     1
$28,345                     1
$38,775                     1
$63,595                     1
$91,495                     1
$59,865                     1
$50,695                     1
$46,500                     1
$44,500                     1
$17,000-$20,000             1
$51,570                     1
$66,575                     1
$41,295                     1
$82,495                     1
$37,490                     1
$44,195                     1
$48,595                     1
$58,590                     1
$149,990                    1
$104,595                    1
$60,495                     1
$41,390                     1
$51,095                     1
$57,095                     1
$59,990                     1
$64,990                     1
$41,290                     1
$14,595                     1
$16,720                     1
$35,915                     1
$26,600                     1
$59,900                     1
$30,695                     1
$42,795                     1
$27,495                     1
$23,100                     1
$33,500                     1
$67,300                     1
$61,595                     1
$55,895                     1
$50,895                     1
$48,295                     1
$46,600                     1
$48,900                     1
$65,900                     1
$43,700                     1
$25,800                     1
$17,595                     1
$24,100                     1
$28,400                     1
$75,700                     1
$29,200                     1
$82,400                     1
$33,900                     1
$14,395                     1
$37,200                     1
$36,100                     1
$31,900                     1
$34,900                     1
$56,400                     1
$64,400                     1
$31,700                     1
$62,495                     1
$66,700                     1
$71,600                     1
$76,700                     1
$29,900                     1
$36,800                     1
$57,400                     1
$61,100                     1
$36,900                     1
$37,100                     1
$105,600                    1
$72,800                     1
$66,800                     1
$36,500                     1
$53,800                     1
$93,800                     1
$38,600                     1
$54,300                     1
$71,505                     1
$73,305                     1
$72,000                     1
$36,300                     1
$28,700                     1
$76,805                     1
$37,700                     1
$112,700                    1
$17,000                     1
$39,500                     1
$51,500                     1
$3,000,000                  1
$3,500,000                  1
$5,800,000                  1
$9,000,000                  1
$18,000,000                 1
$5,000,000                  1
$160,000                    1
$125,000                    1
$55,000 / $65,000           1
$25,000 - $40,000           1
$30,000 - $45,000           1
$15,000 - $25,000           1
$20,000 - $30,000           1
$25,000 - $38,000           1
$35,000 - $55,000           1
$50,000 - $75,000           1
$30,000 - $55,000           1
$26,000 - $38,000           1
$35,000 - $75,000           1
$40,000 - $70,000           1
$45,000 - $75,000           1
$22,000 - $30,000           1
$25,000 - $45,000           1
$43,000 - $61,000           1
$40,000 - $90,000           1
$28,000 - $38,000           1
$50,000 - $55,000           1
$43,455                     1
$29,365                     1
$61,625                     1
$64,540                     1
$79,420                     1
$59,140                     1
$64,695                     1
$84,910                     1
$56,505                     1
$79,560                     1
$16,000 - $18,000           1
$17,000 - $19,000           1
$39,000 - $43,000           1
$25,000 - $35,000           1
$32,000 - $35,000           1
$31,000 - $34,000           1
$29,000 - $32,000           1
$26,000 - $28,000           1
$23,000 - $25,000           1
$17,000 - $20,000           1
$70,000 - $90,000           1
$24,000 - $28,000           1
$21,000 - $25,000           1
$23,000 - $28,000           1
$26,000 - $32,000           1
$29,000 - $36,000           1
$36,000 - $42,000           1
$38,000 - $45,000           1
$27,000 - $33,000           1
$33,000 - $40,000           1
$33,000 - $37,000           1
$28,000 - $33,000           1
$24,000 - $30,000           1
$30,000 - $50,000           1
N/A (Concept Only)          1
$12,000 - $16,000           1
$13,000 - $18,000           1
$9,000 - $12,000            1
$12,000 - $18,000           1
$9,000 - $11,000            1
$20,000 - $22,000           1
$28,000 - $32,000           1
$13,000 - $16,000           1
$14,000 - $16,000           1
$5,000,000 - $7,000,000     1
$43,590  $48,000           1
$25,210  $29,135           1
 33,000                    1
$29,000  $43,000           1

In [21]:
df[df["Cars Prices"] == "$3,200,000 "]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
32,ASTON MARTIN,VALKYRIE,V12,"6,496 cc",1160 hp,402 km/h,2.5 sec,"$3,200,000",Hybrid,2,900 Nm

### The `Car Prices` column is inconsistent
Needs to be removed characters like dollar sing `$`, comas `,`, unknown chracters `?`, any range `($5,000,000 - $7,000,000, 28,000 - $32,000)` and replace `(N/A (Concept Only)` with other value. As well, once cleand review outliers, there are cars that cost more than `$1,000,000`

## Fuel types column

In [22]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [23]:
print(df["Fuel Types"].value_counts().to_string())

Fuel Types
Petrol                     871
Diesel                     106
Electric                    97
Hybrid                      79
Petrol/Diesel               16
Petrol/Hybrid               16
Plug-in Hybrid               5
Diesel/Petrol                4
Hybrid (Petrol)              4
Hydrogen                     3
Petrol, Diesel               3
Petrol/AWD                   2
Petrol, Hybrid               2
plug in hyrbrid              1
Petrol/EV                    1
Hybrid/Electric              1
CNG/Petrol                   1
Hybrid/Petrol                1
Diesel Hybrid                1
Petrol (Hybrid)              1
Hybrid (Gas + Electric)      1
Gas / Hybrid                 1
Hybrid / Plug-in             1

### `Fuel types` column 
There are several values that are essentially the same but differ slightly, such as a comma versus a slash `(Petrol/Diesel, Petrol,Diesel)`. One entry mentions `AWD (All-Wheel Drive)`, which doesn't make sense in this column and should be removed. Each value in this column must be transformed into a unique numeric value.

## Seats column

In [24]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Names              1218 non-null   str
 1   Cars Names                 1218 non-null   str
 2   Engines                    1218 non-null   str
 3   CC/Battery Capacity        1215 non-null   str
 4   HorsePower                 1218 non-null   str
 5   Total Speed                1218 non-null   str
 6   Performance(0 - 100 )KM/H  1212 non-null   str
 7   Cars Prices                1218 non-null   str
 8   Fuel Types                 1218 non-null   str
 9   Seats                      1218 non-null   str
 10  Torque                     1217 non-null   str
dtypes: str(11)
memory usage: 104.8 KB

In [26]:
print(df["Seats"].value_counts().to_string())

Seats
5       692
4       161
7       147
2       136
8        29
6        20
3        14
2+2       5
1         3
26       2
20        1
15        1
12        1
9         1
215      1
27       1
78       1
29       1
212      1

In [27]:
df[df["Seats"] == "12"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
286,Nissan,NV1500,4.0L V6,3954 cc,261 hp,160 km/h,9.5 sec,"$33,000",Petrol,12,385 Nm

In [28]:
df[df["Seats"] == "15"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
255,Nissan,Urvan,2.5L Turbo Diese,NaN,2488 cc,140 km/h,14.0 sec,"$28,000",Diesel,15,356 Nm

In [29]:
df[df["Seats"] == "20"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
241,TOYOTA,COASTER,"4.0L,DIESEL","4,009 cc",134 hp,120 km/h,NaN,"$70,000",Diesel,20,500 Nm

In [30]:
df[df["Seats"] == "9"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
327,Volkswagen,Transporter,2.0L I4 Turbo Diesel,1968 cc,102 - 204 hp,180 km/h,12.2 sec,"$35,000",Diesel,9,340 Nm

In [31]:
df[df["Seats"] == "2+2"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
11,FERRARI,PORTOFINO,V8,"3,900 cc",592 hp,320 km/h,3.2 sec,"$210,000",Petrol,2+2,760 Nm
12,FERRARI,ROMA,V8,"3,900 cc",612 hp,320 km/h,3.4 sec,"$230,000",Petrol,2+2,760 Nm
15,FERRARI,PORTOFINO M,V8,"3,900 cc",612 hp,320 km/h,3.2 sec,"$220,000",Petrol,2+2,760 Nm
16,FERRARI,ROMA SPIDER,V8,"3,900 cc",612 hp,320 km/h,3.4 sec,"$240,000",Petrol,2+2,760 Nm
18,TOYOTA,TOYOTA 86,BOXER-4,"1,998 cc",205 hp,226 km/h,6.4 sec,"$27,000",Petrol,2+2,205 Nm

### `Seats column`
The unknown characters need to be removed `?` `(2?6)`. The cars with high quantity of seats seems to make sense. It's important to mention that `2+2` seat it's a valid scale for cars with two front seats and two small rear seats

In [32]:
print(df["Torque"].value_counts().to_string())

Torque
400 Nm               72
250 Nm               56
350 Nm               39
500 Nm               34
450 Nm               33
519 Nm               22
600 Nm               20
560 Nm               19
850 Nm               19
300 Nm               19
200 Nm               18
624 Nm               17
360 Nm               16
320 Nm               15
900 Nm               14
366 Nm               14
260 Nm               13
700 Nm               12
750 Nm               12
420 Nm               12
355 Nm               12
310 Nm               12
275 Nm               12
430 Nm               12
800 Nm               11
270 Nm               11
230 Nm               11
140 Nm               11
160 Nm               11
180 Nm               11
520 Nm               10
650 Nm               10
280 Nm               10
264 Nm               10
179 Nm               10
1600 Nm              10
380 Nm                9
240 Nm                9
870 Nm                9
550 Nm                9
170 Nm                9
265 Nm                9
362 Nm                9
637 Nm                8
620 Nm                8
570 Nm                8
113 Nm                8
245 Nm                8
210 Nm                8
583 Nm                8
629 Nm                8
205 Nm                7
475 Nm                7
720 Nm                7
220 Nm                7
150 Nm                7
330 Nm                7
770 Nm                6
370 Nm                6
145 Nm                6
130 Nm                6
340 Nm                6
580 Nm                6
353 Nm                6
135 Nm                6
480 Nm                6
100 Nm                6
352 Nm                6
197 Nm                6
630 Nm                5
151 Nm                5
365 Nm                5
1234 Nm               5
15,590 Nm             5
696 Nm                5
690 Nm                4
760 Nm                4
335 Nm                4
290 Nm                4
154 Nm                4
680 Nm                4
441 Nm                4
252 Nm                4
351 Nm                3
840 Nm                3
142 Nm                3
120 Nm                3
95 Nm                 3
385 Nm                3
305 Nm                3
652 Nm                3
190 Nm                3
451 Nm                3
110 Nm                3
470 Nm                3
114 Nm                3
127 Nm                3
413 Nm                3
373 Nm                3
666 Nm                3
60 Nm                 3
100 - 140 Nm          2
685 Nm                2
381 Nm                2
1000 Nm               2
565 Nm                2
950 Nm                2
664 Nm                2
93 Nm                 2
390 Nm                2
356 Nm                2
175 Nm                2
460 Nm                2
106 Nm                2
325 Nm                2
199 Nm                2
217 Nm                2
225 Nm                2
384 Nm                2
206 Nm                2
198 Nm                2
344 Nm                2
528 Nm                2
465 Nm                2
640 Nm                2
1050 Nm               2
345 Nm                2
530 Nm                2
115 Nm                2
967 Nm                2
1,400 Nm              2
617 Nm                2
440 Nm                2
1000+ Nm              2
569 Nm                2
259 Nm                2
422 Nm                2
2500 Nm               2
215 Nm                2
691 Nm                2
405 Nm                2
1,424 Nm              2
678 Nm                2
563 Nm                2
196 Nm                2
141 Nm                2
94 Nm                 2
90 Nm                 2
85 Nm                 2
718 Nm                1
719 Nm                1
651 Nm                1
354 Nm                1
821 Nm                1
395 Nm                1
295 Nm                1
410 Nm                1
132 Nm                1
153 Nm                1
174 Nm                1
156 Nm                1
171 Nm                1
248 Nm                1
139 Nm                1
191 Nm                1
207 Nm                1
780 Nm                1
374 Nm                1
329 Nm                1
186 Nm                1
168 Nm                1
161 Nm                1
392 Nm                1
184 Nm                1
278 Nm                1
103 Nm                1
62 Nm                 1
188 Nm                1
195 Nm                1
525 Nm                1
820 Nm                1
469 Nm                1
113-200 Nm            1
51 Nm                 1
190 Nm / 140 Nm       1
135 Nm / 115 Nm       1
200 Nm / 115 Nm       1
170-260 Nm            1
660 Nm                1
498 Nm                1
559 Nm                1
1,355 Nm              1
10,000 Nm             1
285 Nm                1
548 Nm                1
529 Nm                1
324 Nm                1
885 Nm                1
893 Nm                1
603 Nm                1
236 Nm                1
881 Nm                1
255 Nm                1
1,064 Nm              1
421 Nm                1
246 Nm                1
510 Nm                1
740 Nm                1
2600 Nm               1
3500 Nm               1
2200 Nm               1
2400 Nm               1
1800 Nm               1
1200 Nm               1
365 Nm / 480 Nm       1
625 Nm                1
247 Nm                1
200 - 400 Nm          1
300 - 500 Nm          1
130 - 290 Nm          1
150 - 400 Nm          1
170 - 200 Nm          1
230 - 200 Nm          1
400 - 475 Nm          1
420 - 500 Nm          1
650 - 800 Nm          1
400 - 600 Nm          1
250 - 375 Nm          1
400 - 700 Nm          1
700 - 1,050 Nm        1
1,050 - 1,200 Nm      1
250 - 380 Nm          1
400 - 540 Nm          1
430 Nm (GT Model)     1
1051 Nm               1
210 Nm (Electric)     1
746 Nm                1
847 Nm                1
582 Nm                1
825 Nm                1
542 Nm                1
407 Nm                1
100 - 180 Nm          1
154 - 197 Nm          1
686 Nm                1
181 Nm                1
214 Nm                1
343 Nm                1
173 Nm                1
213 Nm                1
434 Nm                1
271 Nm                1
202 Nm                1
314 Nm                1
165 Nm                1
80 Nm                 1
155 Nm                1
105 Nm                1
45 Nm                 1
239 Nm                1
190  210 Nm          1
190  205 Nm          1
221  400 Nm          1

## `Torque` column
It needs to be removed the word `Nm`, commas, extra information `(GT Model)`, ranges `(200 - 400 Nm)`, special characters `(+, ?)`, and any range or operation `(100 - 180 Nm, 365 Nm / 480 Nm  )` also need to be resolved into a single numeric value.

## General duplicated rows

In [36]:
df[df.duplicated()]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
336,Volkswagen,Golf Cabriolet,1.2L I4 Turbo / 2.0L I4 Turbo,1197 cc / 1984 cc,105 - 210 hp,217 km/h,8.4 sec,"$30,000",Petrol,4,200 Nm
354,Volkswagen,Jetta Hybrid,1.4L I4 Turbo + Electric Motor,1395 cc,170 hp,210 km/h,8.6 sec,"$28,000",Hybrid,5,250 Nm
658,Tata Motors,Tiago EV,Permanent Magnet Synchronous,24 kWh,74 hp,120 km/h,5.7 sec,"$11,000",Electric,5,114 Nm
755,Chevrolet,Tahoe RST,5.3L V8 Gasoline,5300 cc,355 hp,180 km/h,7.4 sec,"$64,100",Petrol,7,519 Nm

# Conclusion
All 11 columns are stored as text (`str`) and require cleaning before any
numeric analysis or modeling is possible. Common issues across columns
include:

- Units embedded in values (`cc`, `hp`, `Nm`, `km/h`, `sec`)
- Currency symbols and thousands separators (`$`, `,`)
- Ranges and multi-value entries that need to be resolved into a single
  number (ex., `100 - 150 hp`, `365 Nm / 480 Nm`)
- Inconsistent casing and duplicate categories (`Nissan` vs `NISSAN`)
- Corrupted/unknown characters, likely from encoding issues (`?`)
- A few domain-specific edge cases: hybrid/electric combined values,
  `2+2` seating configuration, and outlier prices for rare or
  concept-only vehicles.

Also, there are 4 duplicated rows that have to be studied to be deleted
or keept

The next step is to clean each column into a proper numeric or
categorical type, so that descriptive statistics, distributions, and
correlations can be computed.