In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

## Reading data set

In [2]:
df = pd.read_csv("../Cars_Datasets_2025.csv", encoding="latin-1")

In [3]:
df.columns = df.columns.str.strip()

## CLEANING

In [4]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

## `Company Names` column text normalization

In [5]:
# Text normalization
df["Company Names"] = df["Company Names"].str.lower().str.strip()

In [6]:
print(df["Company Names"].value_counts().sort_index().to_string())

Company Names
acura                 27
aston martin          11
audi                  21
bentley                1
bmw                   41
bugatti               10
cadillac              20
chevrolet             58
ferrari                9
ford                  54
gmc                   59
honda                  7
hyundai               23
jaguar land rover     40
jeep                  19
kia                   71
lamborghini           24
mahindra               3
maruti suzuki          3
mazda                 87
mercedes              21
mitsubishi            60
nissan               159
peugeot               54
porsche               96
rolls royce           30
tata motors           29
tesla                 10
toyota                50
volkswagen           109
volvo                 12

#### Unique company names without any variation

In [7]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,ferrari,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,rolls royce,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,mercedes,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,audi,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

# `Car Names` column

In [8]:
df["Cars Names"] = df["Cars Names"].str.strip().str.lower()

In [9]:
print(len(df["Cars Names"].value_counts().to_string()))

53965

In [10]:
len(df["Cars Names"].value_counts())

1199

### This column has 1199 unique values, almost one per row, so encoding it directly would not help the model (it would only memorize rows). It will be dropped, or used only to extract features.

# `Engines` column

Split engine entries with multiple values into separate rows

In [11]:
df[df["Engines"].str.contains('/')]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
271,volkswagen,golf,1.5L Turbo I4 / Electric,1498 cc / 40 - 58 kWh,110 - 320 hp,210 km/h,8.5 sec,"$23,000",Petrol,5,250 Nm
275,volkswagen,polo,1.0L Turbo I3 / 1.6L Diesel,999 cc / 1598 cc,80 - 200 hp,190 km/h,9.5 sec,"$18,000",Petrol,5,175 Nm
279,volkswagen,touareg,3.0L V6 Turbo Diesel / 4.0L V8,2967 cc / 3956 cc,231 - 500 hp,235 km/h,5.9 sec,"$55,000","Petrol, Diesel",5,600 Nm
296,volkswagen,t-cross,1.0L Turbo I3 / 1.5L Turbo I4,999 cc / 1498 cc,95 - 150 hp,200 km/h,10.2 sec,"$25,000",Petrol,5,250 Nm
300,volkswagen,multivan,Plug-in Hybrid / Diesel I4,1395 cc / 1968 cc,150 - 218 hp,190 km/h,9.4 sec,"$50,000","Petrol, Hybrid",7,350 Nm
309,volkswagen,golf variant,1.5L Turbo I4 / 2.0L Diesel I4,1498 cc / 1968 cc,130 - 150 hp,220 km/h,7.5 sec,"$32,000",Petrol,5,320 Nm
311,volkswagen,lupo,1.4L I3 Gas / 1.2L Diesel I3,1390 cc / 1199 cc,60 - 75 hp,170 km/h,14.3 sec,"$15,000",Petrol,4,120 Nm
313,volkswagen,phaeton,3.0L V6 Diesel / 6.0L W12 Gas,2967 cc / 5998 cc,240 - 450 hp,250 km/h,6.1 sec,"$85,000",Petrol,5,560 Nm
314,volkswagen,golf cabriolet,1.2L I4 Turbo / 2.0L I4 Turbo,1197 cc / 1984 cc,105 - 210 hp,217 km/h,8.4 sec,"$30,000",Petrol,4,200 Nm
316,volkswagen,polo vivo,1.4L I4 Gas / 1.6L I4 Gas,1390 cc / 1598 cc,85 - 105 hp,170 km/h,10.8 sec,"$14,000",Petrol,5,132 Nm
318,volkswagen,fox,1.2L I4 Gas / 1.4L I4 Gas,1198 cc / 1390 cc,55 - 75 hp,148 km/h,17.5 sec,"$12,000",Petrol,5,93 Nm
319,volkswagen,vento,1.6L I4 Gas / Diesel,1598 cc,105 - 110 hp,186 km/h,11.7 sec,"$18,000",Petrol,5,153 Nm
321,volkswagen,bora,1.6L I4 Gas / 1.9L I4 Diesel,1598 cc / 1896 cc,100 - 150 hp,200 km/h,9.4 sec,"$20,000",Petrol,5,220 Nm
322,volkswagen,teramont,2.0L I4 Turbo / 3.6L V6 Gas,1984 cc / 3597 cc,235 - 276 hp,190 km/h,8.6 sec,"$32,000",Petrol,7,350 Nm
325,volkswagen,t-roc cabriolet,1.0L I3 Turbo / 1.5L I4 Turbo,999 cc / 1498 cc,115 - 150 hp,205 km/h,9.6 sec,"$35,000",Petrol,4,250 Nm
330,volkswagen,polo tdi,1.4L I4 Diesel / 1.6L Diesel,1390 cc / 1598 cc,75 - 105 hp,190 km/h,9.9 sec,"$20,000",Diesel,5,250 Nm
334,volkswagen,passat b8,1.5L I4 Turbo / 2.0L Diesel,1498 cc / 1968 cc,150 - 280 hp,210 km/h,8.7 sec,"$28,000",Petrol,5,250 Nm
336,volkswagen,golf cabriolet,1.2L I4 Turbo / 2.0L I4 Turbo,1197 cc / 1984 cc,105 - 210 hp,217 km/h,8.4 sec,"$30,000",Petrol,4,200 Nm
340,volkswagen,t-cross r-line,1.0L I3 Turbo / 1.5L I4 Turbo,999 cc / 1498 cc,115 - 150 hp,200 km/h,8.5 sec,"$27,000",Petrol,5,250 Nm
342,volkswagen,passat b7,1.6L Diesel / 2.0L I4 Turbo,1598 cc / 1984 cc,120 - 240 hp,220 km/h,8.5 sec,"$26,000",Petrol,5,280 Nm
352,volkswagen,passat variant,1.5L I4 Turbo / 2.0L Diesel,1498 cc / 1968 cc,150 - 240 hp,220 km/h,8.5 sec,"$30,000",Petrol,5,280 Nm
372,volkswagen,jetta sportwagen,1.4L I4 Turbo / 2.0L Diesel I4,1395 cc / 1968 cc,147 - 150 hp,200 km/h,8.5 sec,"$27,000",Petrol,5,250 Nm
374,volkswagen,touareg v6,3.0L V6 Turbo Diesel / Gasoline,2967 cc,231 - 340 hp,235 km/h,7.5 sec,"$60,000",Petrol,5,450 Nm
630,tata motors,altroz,1.2L Revotron Petrol / 1.5L Diesel,1199 cc / 1497 cc,86 hp / 89 hp,170 km/h,12 sec,"$10,400",Petrol/Diesel,5,113-200 Nm
640,tata motors,zest,1.3L Quadrajet Diesel / 1.2L Revotron Petrol,1248 cc / 1199 cc,75 hp / 90 hp,165 km/h,15 sec,"$8,700",Diesel/Petrol,5,190 Nm / 140 Nm
643,tata motors,indigo marina,1.4L CR4 Diesel / 1.4L Petrol,1396 cc,70 hp / 85 hp,150 km/h,17 sec,"$8,300",Diesel/Petrol,5,135 Nm / 115 Nm
644,tata motors,manza,1.3L Quadrajet Diesel / 1.4L Petrol,1248 cc / 1368 cc,75 hp / 90 hp,160 km/h,14 sec,"$9,000",Diesel/Petrol,5,200 Nm / 115 Nm
648,tata motors,nexon,1.2L Turbo Petrol / 1.5L Diesel,1199 cc / 1497 cc,118 hp / 110 hp,180 km/h,10 sec,"$14,000",Petrol/Diesel,5,170-260 Nm
899,jaguar land rover,jaguar f-type,V6 / V8 Petrol,2995 cc (V6),335 hp,260 km/h,5.1 sec,"$70,000",Petrol,2,450 Nm
905,jaguar land rover,jaguar f-pace,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),250 hp / 340 hp,230 km/h,7.2 sec / 5.4 sec,"$55,000 / $65,000",Petrol,5,365 Nm / 480 Nm
907,jaguar land rover,jaguar f-pace r-dynamic,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),340 hp,250 km/h,5.4 sec,"$65,000",Petrol,5,480 Nm
913,jaguar land rover,jaguar xf r-dynamic,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),340 hp,250 km/h,5.4 sec,"$65,000",Petrol,5,480 Nm
919,jaguar land rover,jaguar f-type r-dynamic,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),300 hp,250 km/h,5.1 sec,"$70,000",Petrol,2,400 Nm
921,jaguar land rover,jaguar xf sportbrake,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),250 hp,250 km/h,6.5 sec,"$60,000",Petrol,5,400 Nm
927,jaguar land rover,jaguar f-pace s awd,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),340 hp,250 km/h,5.4 sec,"$65,000",Petrol,5,480 Nm
930,jaguar land rover,jaguar xe r-sport awd,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),300 hp,250 km/h,5.5 sec,"$55,000",Petrol,5,400 Nm
931,jaguar land rover,jaguar xf portfolio awd,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),340 hp,250 km/h,5.4 sec,"$60,000",Petrol,5,450 Nm
934,jaguar land rover,jaguar f-pace prestige awd,I4 Petrol / V6 Petrol,1999 cc (I4) / 2995 cc (V6),340 hp,250 km/h,5.4 sec,"$65,000",Petrol,5,480 Nm
1014,ford,fusion (mondeo),1.5L EcoBoost / 2.0L Hybrid,"1,500 - 2,000 cc",160 - 250 hp,220 km/h,7.5 sec,"$25,000 - $40,000",Petrol/Hybrid,5,200 - 400 Nm
1015,ford,taurus,3.5L V6 / 2.0L EcoBoost,"2,000 - 3,500 cc",200 - 365 hp,220 km/h,6.5 sec,"$30,000 - $45,000",Petrol,5,300 - 500 Nm
1016,ford,fiesta,1.0L EcoBoost / 1.5L,"1,000 - 1,500 cc",85 - 200 hp,200 km/h,7.0 sec,"$15,000 - $25,000",Petrol,5,130 - 290 Nm
1017,ford,focus,1.0L EcoBoost / 1.5L / 2.0L,"1,000 - 2,000 cc",120 - 300 hp,220 km/h,6.5 sec,"$20,000 - $30,000",Petrol,5,150 - 400 Nm
1019,ford,ecosport,1.0L Turbo Inline-3 / 2.0L,"1,000 - 2,000 cc",123 - 166 hp,180 km/h,9.0 sec,"$20,000 - $25,000",Petrol,5,170 - 200 Nm
1020,ford,escape (kuga),1.5L EcoBoost / 2.5L Hybrid,"1,500 - 2,500 cc",181 - 200 hp,190 km/h,7.5 sec,"$25,000 - $38,000",Petrol/Hybrid,5,230 - 200 Nm
1021,ford,edge,2.0L EcoBoost / 2.7L V6,"2,000 - 2,700 cc",250 - 335 hp,200 km/h,6.5 sec,"$35,000 - $45,000",Petrol,5,400 - 475 Nm
1022,ford,explorer,2.3L EcoBoost / 3.0L V6,"2,300 - 3,000 cc",300 - 400 hp,200 km/h,6.0 sec,"$35,000 - $55,000",Petrol,7,420 - 500 Nm
1023,ford,expedition,3.5L EcoBoost / 5.4L V8,"3,500 - 5,400 cc",375 - 400 hp,180 km/h,6.5 sec,"$50,000 - $75,000",Petrol,8,650 - 800 Nm
1024,ford,bronco,2.3L EcoBoost / 2.7L V6,"2,300 - 2,700 cc",275 - 310 hp,200 km/h,7.5 sec,"$30,000 - $55,000",Petrol,4,400 - 600 Nm
1025,ford,bronco sport,1.5L EcoBoost / 2.0L EcoBoost,"1,500 - 2,000 cc",181 - 250 hp,185 km/h,7.0 sec,"$26,000 - $38,000",Petrol,5,250 - 375 Nm
1026,ford,f-150,3.3L V6 / 5.0L V8 / 3.5L EcoBoost,"3,300 - 5,000 cc",290 - 450 hp,200 km/h,5.0 - 6.5 sec,"$35,000 - $75,000",Petrol/Diesel,5,400 - 700 Nm
1027,ford,f-250 super duty,6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel,"6,200 - 7,300 cc",385 - 475 hp,180 km/h,6.5 - 7.0 sec,"$40,000 - $70,000",Petrol/Diesel,5,"700 - 1,050 Nm"
1028,ford,f-350 super duty,6.7L Turbo-Diesel / 7.3L V8,"6,700 - 7,300 cc",450 - 475 hp,180 km/h,7.0 - 8.0 sec,"$45,000 - $75,000",Diesel,5,"1,050 - 1,200 Nm"
1029,ford,maverick,2.5L Hybrid / 2.0L EcoBoost,"2,500 - 2,000 cc",191 - 250 hp,180 km/h,6.5 - 8.0 sec,"$22,000 - $30,000",Hybrid/Petrol,5,250 - 380 Nm
1030,ford,ranger,2.3L Turbo Inline-4 / 2.7L V6,"2,300 - 2,700 cc",270 - 325 hp,180 km/h,6.0 - 7.0 sec,"$25,000 - $45,000",Petrol/Diesel,5,400 - 540 Nm
1080,mitsubishi,colt,1.1L / 1.5L MIVEC,"1,100 - 1,500 cc",75 - 150 hp,180 km/h,9.0 - 12.0 sec,"$15,000 - $20,000",Petrol,5,100 - 180 Nm
1091,mitsubishi,lancer ex,1.6L MIVEC / 2.0L,"1,600 - 2,000 cc",117 - 148 hp,200 km/h,10.0 sec,"$20,000 - $25,000",Petrol,5,154 - 197 Nm
1095,mitsubishi,delica van,2.0L Diesel / 2.2L Diesel,"2,000 - 2,200 cc",145 hp,175 km/h,11.5 sec,"$30,000 - $35,000",Diesel,7,360 Nm
1215,toyota,corolla cross,2.0L Gas / 2.0L Hybrid,1987 cc / Hybrid batt,169  196 hp,190 km/h,8.0  9.2 sec,"$25,210  $29,135",Gas / Hybrid,5,190  210 Nm
1216,toyota,c-hr+,1.8L / 2.0L Hybrid,1798 / 1987 cc + batt,140  198 hp,180 km/h,7.9  10.5 sec," 33,000",Hybrid,5,190  205 Nm
1217,toyota,rav4 (6th gen),2.5L Hybrid / Plug-in Hybrid,2487 cc + batt,219  302 hp,200 km/h,6.0  8.1 sec,"$29,000  $43,000",Hybrid / Plug-in,5,221  400 Nm

### Splitting `engines` and `cc/capacity` (explode)

When a cell contains multiple values separated by `/` (e.g. `1.5L Turbo / Electric`), it is split into one row per engine.

- New `_cleaned` columns are created; the original columns are left untouched.
- If a column has a single value, it is repeated to match the length.
- Null values are converted to `[None]`.

In [12]:
df["Engines_cleaned"] = df["Engines"]
df["CC/BatteryCapacity_cleaned"] = df["CC/Battery Capacity"]

cols = ["Engines_cleaned", "CC/BatteryCapacity_cleaned"]
def igualate(row):
    n = max(len(row[c]) for c in cols)
    for c in cols:
        if len(row[c]) == 1:
            row[c] = row[c] * n
    return row

for c in cols:
    df[c] = df[c].str.strip().str.split('/')
    df[c] = df[c].apply(lambda x: x if isinstance(x, list) else [None]) 

df = df.apply(igualate, axis=1)
df = df.explode(cols, ignore_index=True)

In [13]:
df["Engines_cleaned"] = df["Engines_cleaned"].str.strip()

### Creating `displacement` column
Extracting displacement in liters from the engine description using a regex (e.g. `2.0L Turbo I4` → `2.0`) and converting it to a numeric column.

In [14]:
df["displacement"] = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)(\d+\.?\d*)\s*L\b")[0]
)
df["displacement"].isna().sum()

np.int64(480)

In [15]:
df.loc[df["displacement"].isna(), "Engines_cleaned"].value_counts().head(30)

Engines_cleaned
I4                                                64
V12                                               51
V6                                                40
Inline-4                                          38
V8                                                34
Dual Electric Motors                              23
Electric Motor                                    21
I4 Petrol                                         21
Electric                                          16
V6 Petrol                                         13
I3                                                12
V10                                               11
I6                                                 9
V8 Petrol                                          9
Hybrid I4                                          7
I4 + ELECTRIC                                      6
Single Electric Motor                              6
ELECTRIC MOTOR                                     5
Permanent Magnet Synchronous                       5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
Turbocharged V6                                    5
Diesel I4                                          4
660cc Inline-3                                     4
Hybrid I4 + Electric Motor                         4
Twin-Turbo V6 Hybrid                               4
ELECTRIC                                           3
Tri Electric Motors                                3
Dual Electric Motors (AWD)                         3
I4 Turbocharged                                    3
Name: count, dtype: int64

Some engines list displacement in cc instead of liters (e.g. `660cc Inline-3`). These values are converted to liters (cc / 1000) and used to fill the missing displacement values.

In [16]:
cc = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)(\d+)\s*cc")[0]
)
df["displacement"] = df["displacement"].fillna(cc / 1000)
df["displacement"].isna().sum()

np.int64(474)

### Creating `cylinders` column

The cylinder count appears in several formats (`V8`, `I4`, `Inline-4`, `Flat-6`, `W16`, `4-Cylinder`...). Each format is extracted with its own regex, and the results are then combined into a single `cylinders` column.

In [17]:
cyl_V = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)V(\d+)")[0]
)

cyl_I = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)I(\d+)")[0]
)

cyl_inline = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)Inline\-*(\d+)")[0]
)

cyl_flat = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)Flat\-*(\d+)")[0]
)

cyl_boxer = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)Boxer\-*(\d+)")[0]
)

cyl_W = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)W\-*(\d+)")[0]
)

cyl_VR = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)VR(\d+)")[0]
)

cyl_cylinder = pd.to_numeric(
    df["Engines_cleaned"].str.extract(r"(?i)(\d+)\-*Cylinder")[0]
)

df["cylinders"] = (cyl_V.fillna(cyl_I).fillna(cyl_inline).fillna(cyl_flat)
    .fillna(cyl_boxer).fillna(cyl_W).fillna(cyl_VR).fillna(cyl_cylinder).fillna(cyl_cylinder)
)

In [18]:
df["cylinders"].isna().sum()

np.int64(267)

In [19]:
df.loc[df["cylinders"].isna(), "Engines_cleaned"].value_counts().head(20)

Engines_cleaned
Dual Electric Motors                              23
Electric Motor                                    21
Electric                                          16
2.0L MIVEC                                         7
2.4L Diesel Turbo                                  7
Single Electric Motor                              6
ELECTRIC MOTOR                                     5
Permanent Magnet Synchronous                       5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
1.2L MIVEC                                         5
2.0L SkyActiv-G                                    5
1.4L CR4 Diesel                                    4
2.0L EcoBoost                                      4
3.2L Diesel Turbo                                  4
2.5L SkyActiv-G                                    4
ELECTRIC                                           3
2.8L,TURBO,DIESEL                                  3
1.6L Diesel                                        3
2.0L Diesel                                        3
Name: count, dtype: int64

Electric motors have no cylinders, so their missing values are set to `0`. The `isna()` condition keeps hybrids (e.g. `Hybrid I4 + Electric Motor`) from being overwritten, since they already have a cylinder count.

In [20]:
mask = (
    (df["Engines_cleaned"].str.lower().str.contains("electric") | df["Engines_cleaned"].str.lower().str.contains("permanent magnet")) &
    df["cylinders"].isna()
)

df.loc[mask, "cylinders"] = 0

In [21]:
df["cylinders"].isna().sum()

np.int64(162)

In [22]:
df.loc[df["cylinders"].isna(), "Engines_cleaned"].value_counts().head(20)

Engines_cleaned
2.0L MIVEC              7
2.4L Diesel Turbo       7
1.2L MIVEC              5
2.0L SkyActiv-G         5
1.4L CR4 Diesel         4
2.0L EcoBoost           4
3.2L Diesel Turbo       4
2.5L SkyActiv-G         4
2.8L,TURBO,DIESEL       3
1.6L Diesel             3
2.0L Diesel             3
1.2L Revotron Petrol    3
1.5L EcoBoost           3
2.0L Hybrid             3
2.0L                    3
2.5L Hybrid             3
EcoBlue Turbo Diesel    3
1.5L MIVEC              3
2.5L Turbocharged       3
1.2L Petrol             2
Name: count, dtype: int64

In [23]:
df.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque,Engines_cleaned,CC/BatteryCapacity_cleaned,displacement,cylinders
0,ferrari,sf90 stradale,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm,V8,3990 cc,NaN,8.0
1,rolls royce,phantom,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm,V12,6749 cc,NaN,12.0
2,ford,ka+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm,1.2L Petrol,"1,200 cc",1.2,NaN
3,mercedes,gt 63 s,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm,V8,"3,982 cc",NaN,8.0
4,audi,audi r8 gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm,V10,"5,204 cc",NaN,10.0

### Creating `is_turbo` column 
Before building the flag, I listed the engines that don't match `turbo`, `supercharged` or `ecoboost` to make sure no turbocharged variant was missed. Then `is_turbo` is created as a binary column (1 = forced induction, 0 = otherwise), and a random sample of flagged rows is reviewed as a sanity check.

In [24]:
text = df["Engines_cleaned"].str.lower()
without_turbo = ~text.str.contains("turbo|supercharged|ecoboost", na=False)
print(text[without_turbo].value_counts().to_string())

Engines_cleaned
i4                                                64
v12                                               51
v6                                                40
inline-4                                          38
v8                                                34
electric motor                                    26
dual electric motors                              23
i4 petrol                                         21
2.0l inline-4                                     20
electric                                          19
1.6l inline-4                                     19
5.6l v8                                           17
5.3l v8 gasoline                                  16
6.2l v8 gasoline                                  15
1.8l inline-4                                     13
v6 petrol                                         13
i3                                                12
3.5l v6                                           12
3.6l v6 gasoline                                  12
v10                                               11
2.0l 4-cylinder                                   11
2.0l diesel i4                                    10
4.0l naturally aspirated flat-6                   10
i6                                                 9
3.8l v6                                            9
1.5l inline-4                                      9
3.0l v6                                            9
v8 petrol                                          9
3.6l v6 engine                                     7
2.5l 4-cylinder                                    7
hybrid i4                                          7
2.0l mivec                                         7
i4 + electric                                      6
2.5l inline-4                                      6
2.5l v6                                            6
single electric motor                              6
6.6l v8 diesel                                     6
5.3l v8 engine                                     6
6.6l v8 engine                                     6
6.2l v8 engine                                     6
permanent magnet synchronous                       5
3.6l v6 pentastar gasoline                         5
electric motors with up to 11,500 lb-ft torque     5
electric (dual motor)                              5
1.2l mivec                                         5
0.7l 3-cylinder                                    5
2.0l skyactiv-g                                    5
2.0l hybrid                                        4
3.3l v6                                            4
diesel i4                                          4
1.2l diesel i3                                     4
660cc inline-3                                     4
1.2l revotron 3-cylinder petrol                    4
1.4l cr4 diesel                                    4
1.6l 4-cylinder                                    4
hybrid i4 + electric motor                         4
1.6l 4-cylinder hybrid                             4
2.5l skyactiv-g                                    4
1.2l,4-cylinder,inline-4(i4)                       3
1.6l diesel                                        3
4.0l v6                                            3
1.6l i4 gas                                        3
2.0l diesel                                        3
3.7l v6                                            3
5.0l v8                                            3
2.4l inline-4                                      3
2.5l inline-4 diesel                               3
4.5l v8                                            3
1.2l revotron petrol                               3
tri electric motors                                3
dual electric motors (awd)                         3
1.4l inline-4 gasoline                             3
2.0l                                               3
2.5l hybrid                                        3
2.7l v6                                            3
1.5l mivec                                         3
1.3l inline-4                                      3
1.3l inline-2 (wankel)                             3
1.2l petrol                                        2
boxer-4                                            2
2.0l,4-cylinder,inline-4(i4)                       2
2.2l,4-cylinder,inline-4(i4)                       2
plug-in hybrid                                     2
1.4l i4 gas                                        2
1.2l i4 gas                                        2
1.8l i4 gas                                        2
1.5l inline-4 diesel                               2
4.8l inline-6                                      2
2.3l inline-4 diesel                               2
3.0l inline-4 diesel                               2
2.4l inline-6                                      2
2.9l v6 + electric motor                           2
4.0l v8 + electric motor                           2
3.0l v6 + electric motor                           2
1.5l diesel                                        2
1.3l quadrajet diesel                              2
1.4l petrol                                        2
2.2l dicor diesel                                  2
single electric motor (rwd)                        2
4.3l v6 gasoline                                   2
dual-motor electric                                2
2.5l i4 engine                                     2
v6 hybrid                                          2
1.5l                                               2
7.3l v8                                            2
v8 gasoline engine                                 2
i4 hybrid                                          2
2.4l hybrid                                        2
1.6l mivec                                         2
2.2l diesel                                        2
1.8l mivec                                         2
1.3l wankel + electric                             2
1.3l wankel rotary engine                          2
hybrid                                             1
1.4l,4-cylinder,inline-4(i4)                       1
1.5l,4-cylinder,inline(i4)                         1
2.0l,4-cylinder,with hybrid system                 1
2.0l,inline-4                                      1
hydrogen fuel cell,electric motor                  1
2.5l,inline-4,hybrid,or 3.5l,v6                    1
4.0l,diesel                                        1
1.5l,hybrid                                        1
1.0l,inline-3                                      1
3.5l,v6,plug in hybrid                             1
1.8l,hybrid                                        1
1.6l petrol + plug in hybrid system                1
1.6l petrol                                        1
4.0l v8                                            1
plug-in hybrid v6                                  1
electric awd                                       1
1.4l i3 gas                                        1
2.9l vr6                                           1
3.0l v6 diesel                                     1
6.0l w12 gas                                       1
1.5l i4 gas                                        1
diesel                                             1
1.9l i4 diesel                                     1
3.6l v6 gas                                        1
1.4l i4 diesel                                     1
3.2l vr6                                           1
plug-in hybrid (0.8l i2 diesel)                    1
1.5l i4 cng                                        1
gasoline                                           1
1.2l inline-3 hybrid                               1
1.2l inline-3                                      1
2.0l inline-4 hybrid                               1
2.0l inline-6                                      1
2.5l inline-4 hybrid                               1
1.4l inline-4                                      1
2.8l inline-6 diesel                               1
2.7l inline-4 diesel                               1
1.5l hybrid                                        1
1.2l hybrid                                        1
4.2l inline-6                                      1
4.1l v8                                            1
2.8l inline-6                                      1
4.2l naturally aspirated flat-6                    1
1.2l revotron bi-fuel                              1
624cc mpfi                                         1
1.2l mpfi petrol                                   1
1.4l mpfi petrol                                   1
2.2l varicor diesel                                1
3.0l cr4 diesel                                    1
quad electric motors                               1
2.4l i4 tigershark gasoline                        1
5.7l v8 gasoline with etorque                      1
6.4l v8 gasoline                                   1
1.5l 4-cylinder                                    1
5.7l v8 gasoline                                   1
3.2l v6 pentastar gasoline                         1
6.4l v8 hemi gasoline                              1
6.6l v8 gasoline                                   1
2.5l inline-4 gasoline                             1
4.3l v6 engine                                     1
electric motors with advanced awd                  1
hybrid i4+ electric motor                          1
i4 petrol + electric motor                         1
inline-4 hybrid                                    1
5.4l v8                                            1
6.2l v8                                            1
2.5l inline-4 + electric                           1
3.3l v6 + electric                                 1
naturally aspirated v6                             1
inline-4 gasoline engine                           1
naturally aspirated v8                             1
v6 hybrid + electric motor                         1
1.1l                                               1
2.4l mivec                                         1
3.0l diesel                                        1
2.4l phev                                          1
7.5l diesel                                        1
3.0l diesel hybrid                                 1
2.4l petrol                                        1
2.4l 4-cylinder                                    1
2.5l diesel                                        1
1.2l rotary                                        1
rotary skyactiv-r                                  1
1.5l skyactiv-g                                    1
2.3l miller cycle v6                               1
1.3l rotary                                        1
1.8l rotary                                        1
2.6l inline-4                                      1
3.0l inline-4                                      1
3.0l inline-6                                      1
1.2l inline-4                                      1
1.6l inline-2 (wankel)                             1
1.0l inline-2 (wankel)                             1
0.36l inline-2                                     1
0.66l inline-3                                     1
2.6l wankel rotary engine                          1
2.5l hybrid i4                                     1
2.0l gas                                           1
1.8l                                               1

In [25]:
df["is_turbo"] = text.str.contains("turbo|supercharged|ecoboost")

In [26]:
df.loc[df["is_turbo"] == 1, "Engines_cleaned"].sample(10)

573        2.9L V6 Twin Turbo
1105    Turbocharged Inline-4
339             2.0L I4 Turbo
327             2.0L I4 Turbo
1006          Turbocharged V6
345             2.0L I4 Turbo
354             1.5L I4 Turbo
394             2.0L I4 Turbo
1070            2.0L EcoBoost
240         2.8L,TURBO,DIESEL
Name: Engines_cleaned, dtype: str

In [27]:
text = text.str.strip()
df["is_hybrid"] = text.str.contains(r"hybrid|phev|plug|\+\s*electric", na=False).astype(int)

In [28]:
print(df.loc[df["is_hybrid"]==0, "Engines_cleaned"].value_counts().to_string())

Engines_cleaned
I4                                                64
V12                                               51
V6                                                40
Inline-4                                          38
V8                                                34
Dual Electric Motors                              23
Electric Motor                                    21
I4 Petrol                                         21
2.0L Inline-4                                     20
1.6L Inline-4                                     19
2.0L I4 Turbo                                     19
5.6L V8                                           17
Electric                                          16
5.3L V8 Gasoline                                  16
3.0L Twin-Turbo Flat-6                            15
6.2L V8 Gasoline                                  15
2.0L Turbo I4                                     14
1.8L Inline-4                                     13
V6 Petrol                                         13
I3                                                12
3.5L V6                                           12
3.6L V6 Gasoline                                  12
V10                                               11
2.0L 4-Cylinder                                   11
2.0L Diesel I4                                    10
4.0L Naturally Aspirated Flat-6                   10
8.0L Quad-Turbo W16                               10
I6                                                 9
3.8L V6                                            9
1.5L Inline-4                                      9
3.0L V6                                            9
2.0L Turbo Inline-4                                9
1.6L Turbocharged 4-Cylinder                       9
V8 Petrol                                          9
3.0L Twin-Turbo V6                                 8
2.9L V6 Twin Turbo                                 8
2.0L Turbo Inline-4 Gasoline                       8
1.5L Turbo I4                                      7
3.8L Twin-Turbo Flat-6                             7
2.9L Twin-Turbo V6                                 7
3.6L V6 engine                                     7
2.5L 4-Cylinder                                    7
2.0L MIVEC                                         7
2.4L Diesel Turbo                                  7
2.5L Inline-4                                      6
2.5L V6                                            6
Single Electric Motor                              6
1.5L Turbo Inline-4 Gasoline                       6
6.6L V8 Diesel                                     6
5.3L V8 engine                                     6
6.6L V8 engine                                     6
6.2L V8 engine                                     6
ELECTRIC MOTOR                                     5
1.5L I4 Turbo                                      5
3.8L Twin-Turbo V6                                 5
4.0L Twin-Turbo V8                                 5
Permanent Magnet Synchronous                       5
3.6L V6 Pentastar Gasoline                         5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
Turbocharged V6                                    5
1.2L MIVEC                                         5
0.7L 3-Cylinder                                    5
2.0L SkyActiv-G                                    5
3.3L V6                                            4
3.0L V6 Turbo Diesel                               4
Diesel I4                                          4
1.2L Diesel I3                                     4
1.0L I3 Turbo                                      4
1.0L Turbocharged Inline-3                         4
660cc Inline-3                                     4
3.0L V6 Turbo                                      4
4.0L V8 Twin Turbo                                 4
1.2L Revotron 3-cylinder Petrol                    4
1.4L CR4 Diesel                                    4
2.7L Turbo 4-cylinder                              4
1.6L 4-Cylinder                                    4
12.8L I6 Turbo Diesel                              4
2.0L EcoBoost                                      4
3.2L Diesel Turbo                                  4
2.5L SkyActiv-G                                    4
ELECTRIC                                           3
1.2L,4-CYLINDER,INLINE-4(I4)                       3
2.8L,TURBO,DIESEL                                  3
1.0L Turbo I3                                      3
1.6L Diesel                                        3
4.0L V6                                            3
2.0L Turbo Diesel I4                               3
1.6L I4 Gas                                        3
2.0L Diesel                                        3
3.7L V6                                            3
1.5L Turbo Inline-3                                3
5.0L V8                                            3
2.4L Inline-4                                      3
2.5L Inline-4 Diesel                               3
4.5L V8                                            3
2.7L Turbo Inline-4 Gasoline                       3
1.2L Revotron Petrol                               3
Tri Electric Motors                                3
Dual Electric Motors (AWD)                         3
6.2L Supercharged V8 Gasoline                      3
1.4L Inline-4 Gasoline                             3
1.5L Turbo 4-cylinder                              3
1.5L Turbocharged I4 engine                        3
2.5L Turbocharged 4-Cylinder                       3
I4 Turbocharged                                    3
1.5L EcoBoost                                      3
2.0L                                               3
2.7L V6                                            3
EcoBlue Turbo Diesel                               3
1.5L MIVEC                                         3
2.5L Turbocharged                                  3
1.3L Inline-4                                      3
1.3L Inline-2 (Wankel)                             3
1.2L Petrol                                        2
BOXER-4                                            2
2.0L,4-CYLINDER,INLINE-4(I4)                       2
2.2L,4-CYLINDER,INLINE-4(I4)                       2
1.6L,TURBOCHARGED INLINE-3                         2
1.2L I4 Turbo                                      2
1.4L I4 Gas                                        2
1.2L I4 Gas                                        2
4.0L V8 Turbo Diesel                               2
1.4L I4 Turbo                                      2
1.8L I4 Gas                                        2
1.5L Inline-4 Diesel                               2
3.0L V6 Twin-Turbo                                 2
4.8L Inline-6                                      2
2.3L Inline-4 Diesel                               2
3.0L Inline-4 Diesel                               2
2.4L Inline-6                                      2
2.0L Turbo Flat-4                                  2
3.0L Turbocharged V6                               2
1.5L Diesel                                        2
1.3L Quadrajet Diesel                              2
1.4L Petrol                                        2
2.0L Kryotec Turbocharged Diesel                   2
2.2L Dicor Diesel                                  2
Single Electric Motor (RWD)                        2
4.3L V6 Gasoline                                   2
Dual-Motor Electric                                2
2.5L I4 engine                                     2
13.0L I6 Turbo Diesel                              2
1.0L EcoBoost                                      2
1.5L                                               2
2.3L EcoBoost                                      2
3.5L EcoBoost                                      2
7.3L V8                                            2
6.7L Turbo-Diesel                                  2
2.3L Turbo Inline-4                                2
3.5L Twin-Turbo V6                                 2
Turbocharged Inline-4                              2
Turbocharged V8 Diesel                             2
V8 Gasoline Engine                                 2
1.5L Turbo                                         2
1.6L MIVEC                                         2
2.2L Diesel                                        2
1.8L MIVEC                                         2
1.3L Wankel Rotary Engine                          2
1.4L,4-CYLINDER,INLINE-4(I4)                       1
1.5L,4-CYLINDER,INLINE(I4)                         1
3.3L,V6,TWIN TURBO DIESEL                          1
2.0L,INLINE-4                                      1
HYDROGEN FUEL CELL,ELECTRIC MOTOR                  1
4.0L,DIESEL                                        1
1.0L,INLINE-3                                      1
2.5L Turbocharged Inline-4                         1
1.6L PETROL                                        1
2.5L Turbo Diese                                   1
1.6L Turbo GDI 4-cylinder                          1
4.0L V8                                            1
Electric AWD                                       1
1.4L I3 Gas                                        1
2.9L VR6                                           1
3.0L V6 Diesel                                     1
6.0L W12 Gas                                       1
1.5L I4 Gas                                        1
Diesel                                             1
1.9L I4 Diesel                                     1
3.6L V6 Gas                                        1
2.0L I4 Turbo Diesel                               1
1.4L I4 Diesel                                     1
3.2L VR6                                           1
1.6L Turbocharged Rally Engine                     1
1.5L I4 CNG                                        1
Gasoline                                           1
1.3L Turbocharged Inline-4                         1
1.5L Turbocharged Inline-3                         1
1.2L Turbocharged Inline-4                         1
1.2L Inline-3                                      1
2.0L Inline-6                                      1
1.6L Turbo Inline-4                                1
2.6L Twin-Turbo Inline-6                           1
2.0L VC-Turbo Inline-4                             1
1.4L Inline-4                                      1
2.8L Inline-6 Diesel                               1
2.7L Inline-4 Diesel                               1
3.5L Twin-Turbo V8                                 1
1.0L Turbo Inline-4                                1
2.7L Turbo Diesel                                  1
4.2L Inline-6                                      1
4.1L V8                                            1
2.8L Inline-6                                      1
1.8L Turbo Inline-4                                1
3.0L Flat-6 Twin Turbo                             1
2.0L Turbocharged Flat-4                           1
2.5L Turbocharged Flat-4                           1
3.0L Turbo Diesel V6                               1
3.0L Twin-Turbo V6 Gasoline                        1
4.2L Naturally Aspirated Flat-6                    1
1.2L Turbocharged Petrol                           1
1.2L Revotron Bi-Fuel                              1
624cc MPFI                                         1
1.2L MPFI Petrol                                   1
1.4L MPFI Petrol                                   1
1.2L Turbo Petrol                                  1
2.2L Varicor Diesel                                1
3.0L CR4 Diesel                                    1
Quad Electric Motors                               1
2.0L Turbo I4 Gasoline                             1
2.4L I4 Tigershark Gasoline                        1
2.0L Turbo Gasoline                                1
1.3L Turbo I4 Gasoline                             1
5.7L V8 Gasoline with eTorque                      1
6.4L V8 Gasoline                                   1
1.5L 4-Cylinder                                    1
5.7L V8 Gasoline                                   1
3.2L V6 Pentastar Gasoline                         1
6.4L V8 HEMI Gasoline                              1
3.6L Twin-Turbo V6 Gasoline                        1
1.4L Turbo Inline-4 Gasoline                       1
6.6L V8 Gasoline                                   1
1.3L Turbo Inline-3 Gasoline                       1
2.8L Turbo Diesel I4                               1
1.2L Turbo Inline-3 Gasoline                       1
2.5L Inline-4 Gasoline                             1
2.0L Turbo 4-cylinder                              1
2.7L Turbo engine                                  1
4.3L V6 engine                                     1
Electric motors with advanced AWD                  1
3.3L Turbocharged V6                               1
16.1L I6 Turbo Diesel                              1
7.7L I6 Turbo Diesel                               1
5.1L I4 Turbo Diesel                               1
Inline-4 Turbocharged                              1
Turbocharged I4                                    1
1.0L Turbo Inline-3                                1
5.4L V8                                            1
6.2L V8                                            1
2.7L Twin-Turbo V6                                 1
Turbocharged Inline-3                              1
Naturally Aspirated V6                             1
Inline-4 Gasoline Engine                           1
Supercharged V8                                    1
Naturally Aspirated V8                             1
I4 Turbo Diesel                                    1
V6 EcoBoost                                        1
V6 Turbocharged                                    1
2.0L Turbocharged                                  1
2.2L Diesel Turbo                                  1
1.1L                                               1
2.4L MIVEC                                         1
3.0L Diesel                                        1
7.5L Diesel                                        1
2.4L Petrol                                        1
2.4L 4-Cylinder                                    1
1.5L Turbocharged                                  1
3.3L Inline-6 Turbo                                1
2.3L Turbocharged                                  1
2.5L Diesel                                        1
3.2L Turbo Diesel                                  1
1.3L Rotary Twin-Turbo                             1
1.2L Rotary                                        1
Rotary SkyActiv-R                                  1
1.5L SkyActiv-G                                    1
2.3L Miller Cycle V6                               1
2.0L Twin-Rotor Turbo                              1
1.3L Rotary                                        1
1.8L Rotary                                        1
657cc Turbocharged Inline-3                        1
2.6L Inline-4                                      1
3.0L Inline-4                                      1
3.0L Inline-6                                      1
1.2L Inline-4                                      1
1.6L Inline-2 (Wankel)                             1
1.0L Inline-2 (Wankel)                             1
0.36L Inline-2                                     1
0.66L Inline-3                                     1
2.6L Wankel Rotary Engine                          1
2.0L Gas                                           1
1.8L                                               1

### Creating `is_diesel` column
Flags diesel engines (1 = diesel, 0 = otherwise). The pattern `diesel?` also catches a typo in the source data (`Turbo Diese`).

In [29]:
df["is_diesel"] = text.str.contains(r"diesel?", na=False).astype(int)

In [30]:
print(df.loc[df["is_diesel"]==0, "Engines_cleaned"].value_counts().to_string())

Engines_cleaned
I4                                                64
V12                                               51
V6                                                40
Inline-4                                          38
V8                                                34
Dual Electric Motors                              23
Electric Motor                                    21
I4 Petrol                                         21
2.0L Inline-4                                     20
1.6L Inline-4                                     19
2.0L I4 Turbo                                     19
5.6L V8                                           17
Electric                                          16
5.3L V8 Gasoline                                  16
3.0L Twin-Turbo Flat-6                            15
6.2L V8 Gasoline                                  15
2.0L Turbo I4                                     14
1.8L Inline-4                                     13
V6 Petrol                                         13
I3                                                12
3.5L V6                                           12
3.6L V6 Gasoline                                  12
V10                                               11
2.0L 4-Cylinder                                   11
4.0L Naturally Aspirated Flat-6                   10
8.0L Quad-Turbo W16                               10
I6                                                 9
3.8L V6                                            9
1.5L Inline-4                                      9
3.0L V6                                            9
2.0L Turbo Inline-4                                9
1.6L Turbocharged 4-Cylinder                       9
V8 Petrol                                          9
3.0L Twin-Turbo V6                                 8
2.9L V6 Twin Turbo                                 8
2.0L Turbo Inline-4 Gasoline                       8
1.5L Turbo I4                                      7
3.8L Twin-Turbo Flat-6                             7
2.9L Twin-Turbo V6                                 7
3.6L V6 engine                                     7
2.5L 4-Cylinder                                    7
Hybrid I4                                          7
2.0L MIVEC                                         7
I4 + ELECTRIC                                      6
2.5L Inline-4                                      6
2.5L V6                                            6
Single Electric Motor                              6
1.5L Turbo Inline-4 Gasoline                       6
5.3L V8 engine                                     6
6.6L V8 engine                                     6
6.2L V8 engine                                     6
ELECTRIC MOTOR                                     5
1.5L I4 Turbo                                      5
3.8L Twin-Turbo V6                                 5
4.0L Twin-Turbo V8                                 5
Permanent Magnet Synchronous                       5
3.6L V6 Pentastar Gasoline                         5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
Turbocharged V6                                    5
1.2L MIVEC                                         5
0.7L 3-Cylinder                                    5
2.0L SkyActiv-G                                    5
3.3L V6                                            4
1.0L I3 Turbo                                      4
1.4L I4 Turbo + Electric Motor                     4
1.0L Turbocharged Inline-3                         4
660cc Inline-3                                     4
3.0L V6 Turbo                                      4
4.0L V8 Twin Turbo                                 4
1.2L Revotron 3-cylinder Petrol                    4
2.7L Turbo 4-cylinder                              4
1.6L 4-Cylinder                                    4
Hybrid I4 + Electric Motor                         4
1.6L 4-Cylinder Hybrid                             4
1.6L Hybrid Turbocharged 4-Cylinder                4
Twin-Turbo V6 Hybrid                               4
2.0L EcoBoost                                      4
2.5L SkyActiv-G                                    4
ELECTRIC                                           3
1.2L,4-CYLINDER,INLINE-4(I4)                       3
1.0L Turbo I3                                      3
4.0L V6                                            3
1.6L I4 Gas                                        3
3.7L V6                                            3
1.5L Turbo Inline-3                                3
5.0L V8                                            3
2.4L Inline-4                                      3
4.5L V8                                            3
4.0L Twin-Turbo V8 + Electric Motor                3
2.7L Turbo Inline-4 Gasoline                       3
1.2L Revotron Petrol                               3
Tri Electric Motors                                3
Dual Electric Motors (AWD)                         3
6.2L Supercharged V8 Gasoline                      3
1.4L Inline-4 Gasoline                             3
1.5L Turbo 4-cylinder                              3
1.5L Turbocharged I4 engine                        3
2.5L Turbocharged 4-Cylinder                       3
I4 Turbocharged                                    3
1.5L EcoBoost                                      3
2.0L Hybrid                                        3
2.0L                                               3
2.5L Hybrid                                        3
2.7L V6                                            3
1.5L MIVEC                                         3
2.5L Turbocharged                                  3
1.3L Inline-4                                      3
1.3L Inline-2 (Wankel)                             3
1.2L Petrol                                        2
BOXER-4                                            2
2.0L,4-CYLINDER,INLINE-4(I4)                       2
2.2L,4-CYLINDER,INLINE-4(I4)                       2
1.6L,TURBOCHARGED INLINE-3                         2
Plug-in Hybrid                                     2
1.2L I4 Turbo                                      2
1.4L I4 Gas                                        2
1.2L I4 Gas                                        2
1.4L I4 Turbo                                      2
1.8L I4 Gas                                        2
3.0L V6 Twin-Turbo                                 2
4.8L Inline-6                                      2
1.5L Turbo Hybrid                                  2
2.4L Inline-6                                      2
2.9L V6 + Electric Motor                           2
4.0L V8 + Electric Motor                           2
2.0L Turbo Flat-4                                  2
2.9L Twin-Turbo V6 + Electric Motor                2
3.0L Turbocharged V6                               2
3.0L V6 + Electric Motor                           2
1.4L Petrol                                        2
Single Electric Motor (RWD)                        2
2.0L Turbo PHEV                                    2
1.3L Turbo PHEV                                    2
4.3L V6 Gasoline                                   2
Dual-Motor Electric                                2
2.5L I4 engine                                     2
V6 Hybrid                                          2
1.0L EcoBoost                                      2
1.5L                                               2
2.3L EcoBoost                                      2
3.5L EcoBoost                                      2
7.3L V8                                            2
2.3L Turbo Inline-4                                2
3.5L Twin-Turbo V6                                 2
Turbocharged Inline-4                              2
V8 Gasoline Engine                                 2
I4 Hybrid                                          2
2.4L Hybrid                                        2
1.5L Turbo                                         2
1.6L MIVEC                                         2
1.8L MIVEC                                         2
1.3L Wankel + Electric                             2
1.3L Wankel Rotary Engine                          2
HYBRID                                             1
1.4L,4-CYLINDER,INLINE-4(I4)                       1
1.5L,4-CYLINDER,INLINE(I4)                         1
2.0L,4-CYLINDER,WITH HYBRID SYSTEM                 1
3.5L,V6,HYBRID TWIN-TURBO                          1
2.0L,INLINE-4                                      1
HYDROGEN FUEL CELL,ELECTRIC MOTOR                  1
2.5L,INLINE-4,HYBRID,OR 3.5L,V6                    1
2.0L HYBRID                                        1
1.5L,HYBRID                                        1
1.0L,INLINE-3                                      1
3.5L,V6,PLUG IN HYBRID                             1
1.8L,HYBRID                                        1
1.6L PETROL + PLUG IN HYBRID SYSTEM                1
2.5L Turbocharged Inline-4                         1
1.6L PETROL                                        1
1.6L Turbo GDI 4-cylinder                          1
4.0L V8                                            1
Plug-in Hybrid V6                                  1
Electric AWD                                       1
1.4L I3 Gas                                        1
2.9L VR6                                           1
6.0L W12 Gas                                       1
1.5L I4 Gas                                        1
3.6L V6 Gas                                        1
Plug-in Hybrid (1.4L I4 Turbo)                     1
3.2L VR6                                           1
1.6L Turbocharged Rally Engine                     1
1.5L I4 CNG                                        1
Gasoline                                           1
1.3L Turbocharged Inline-4                         1
1.5L Turbocharged Inline-3                         1
1.2L Inline-3 Hybrid                               1
1.2L Turbocharged Inline-4                         1
1.2L Inline-3                                      1
2.0L Inline-4 Hybrid                               1
2.0L Inline-6                                      1
2.5L Inline-4 Hybrid                               1
1.3L Turbo Hybrid Inline-4                         1
1.6L Turbo Inline-4                                1
2.6L Twin-Turbo Inline-6                           1
2.0L VC-Turbo Inline-4                             1
1.4L Inline-4                                      1
3.0L Twin-Turbo V6 Hybrid                          1
3.5L Twin-Turbo V8                                 1
1.0L Turbo Inline-4                                1
1.5L Hybrid                                        1
1.2L Hybrid                                        1
4.2L Inline-6                                      1
4.1L V8                                            1
2.8L Inline-6                                      1
1.8L Turbo Inline-4                                1
3.0L Flat-6 Twin Turbo                             1
2.0L Turbocharged Flat-4                           1
2.5L Turbocharged Flat-4                           1
3.0L Twin-Turbo V6 Gasoline                        1
4.2L Naturally Aspirated Flat-6                    1
1.2L Turbocharged Petrol                           1
1.2L Revotron Bi-Fuel                              1
624cc MPFI                                         1
1.2L MPFI Petrol                                   1
1.4L MPFI Petrol                                   1
1.2L Turbo Petrol                                  1
Quad Electric Motors                               1
2.0L Turbo I4 Gasoline                             1
2.4L I4 Tigershark Gasoline                        1
2.0L Turbo Gasoline                                1
1.3L Turbo I4 Gasoline                             1
5.7L V8 Gasoline with eTorque                      1
6.4L V8 Gasoline                                   1
1.5L 4-Cylinder                                    1
5.7L V8 Gasoline                                   1
3.2L V6 Pentastar Gasoline                         1
6.4L V8 HEMI Gasoline                              1
3.6L Twin-Turbo V6 Gasoline                        1
1.4L Turbo Inline-4 Gasoline                       1
6.6L V8 Gasoline                                   1
1.3L Turbo Inline-3 Gasoline                       1
1.2L Turbo Inline-3 Gasoline                       1
2.5L Inline-4 Gasoline                             1
2.0L Turbo 4-cylinder                              1
2.7L Turbo engine                                  1
4.3L V6 engine                                     1
Electric motors with advanced AWD                  1
3.3L Turbocharged V6                               1
2.5L Hybrid Turbocharged 4-Cylinder                1
Hybrid I4+ Electric Motor                          1
I4 Petrol + Electric Motor                         1
Inline-4 Hybrid                                    1
Inline-4 Turbocharged                              1
Turbocharged I4                                    1
1.0L Turbo Inline-3                                1
5.4L V8                                            1
6.2L V8                                            1
2.5L Inline-4 + Electric                           1
3.3L V6 + Electric                                 1
2.7L Twin-Turbo V6                                 1
Turbocharged Inline-3                              1
Naturally Aspirated V6                             1
Inline-4 Gasoline Engine                           1
Supercharged V8                                    1
Naturally Aspirated V8                             1
V6 Hybrid + Electric Motor                         1
V6 EcoBoost                                        1
V6 Turbocharged                                    1
2.0L Turbocharged                                  1
1.1L                                               1
2.4L MIVEC                                         1
2.4L PHEV                                          1
2.4L Petrol                                        1
2.4L 4-Cylinder                                    1
1.5L Turbocharged                                  1
3.3L Inline-6 Turbo                                1
2.3L Turbocharged                                  1
1.3L Rotary Twin-Turbo                             1
1.2L Rotary                                        1
Rotary SkyActiv-R                                  1
1.5L SkyActiv-G                                    1
2.3L Miller Cycle V6                               1
2.0L Twin-Rotor Turbo                              1
1.3L Rotary                                        1
1.8L Rotary                                        1
657cc Turbocharged Inline-3                        1
2.6L Inline-4                                      1
3.0L Inline-4                                      1
3.0L Inline-6                                      1
1.2L Inline-4                                      1
1.6L Inline-2 (Wankel)                             1
1.0L Inline-2 (Wankel)                             1
0.36L Inline-2                                     1
0.66L Inline-3                                     1
2.6L Wankel Rotary Engine                          1
2.5L Hybrid I4                                     1
2.4L Turbo I4 (i-FORCE MAX Hybrid)                 1
2.0L Gas                                           1
1.8L                                               1

### Creating `is_electric` column
Flags fully electric powertrains (1 = electric, 0 = otherwise). The pattern covers `electric`, `permanent magnet` and `fuel cell` motors. Hybrids that mention an electric motor (e.g. `I4 + Electric Motor`) are excluded using `is_hybrid`, since they also have a combustion engine.

In [31]:
mask = (
    df["Engines_cleaned"].str.lower().str.strip().str.contains("electric|permanent magnet|fuel cell") &
    (df["is_hybrid"] == 0)
)

df["is_electric"] = mask.astype(int)

In [32]:
df.loc[df["is_electric"] == 0, "Engines_cleaned"]

0                   V8
1                  V12
2          1.2L Petrol
3                   V8
4                  V10
             ...
1281       2.0L Hybrid
1282              1.8L
1283       2.0L Hybrid
1284       2.5L Hybrid
1285    Plug-in Hybrid
Name: Engines_cleaned, Length: 1183, dtype: str

### Creating `is_rotatory` column
Flags rotary (Wankel) engines (1 = rotary, 0 = otherwise). The pattern covers `rotary`, `wankel` and `rotor`, the different ways these engines are named in the data.

In [33]:
df["is_rotatory"] = text.str.lower().str.strip().str.contains("rotary|wankel|rotor", na=False).astype(int)

In [34]:
print(df.loc[df["is_rotatory"] == 0, "Engines_cleaned"].value_counts().to_string())

Engines_cleaned
I4                                                64
V12                                               51
V6                                                40
Inline-4                                          38
V8                                                34
Dual Electric Motors                              23
Electric Motor                                    21
I4 Petrol                                         21
2.0L Inline-4                                     20
1.6L Inline-4                                     19
2.0L I4 Turbo                                     19
5.6L V8                                           17
Electric                                          16
5.3L V8 Gasoline                                  16
3.0L Twin-Turbo Flat-6                            15
6.2L V8 Gasoline                                  15
2.0L Turbo I4                                     14
1.8L Inline-4                                     13
V6 Petrol                                         13
I3                                                12
3.5L V6                                           12
3.6L V6 Gasoline                                  12
V10                                               11
2.0L 4-Cylinder                                   11
2.0L Diesel I4                                    10
4.0L Naturally Aspirated Flat-6                   10
8.0L Quad-Turbo W16                               10
I6                                                 9
3.8L V6                                            9
1.5L Inline-4                                      9
3.0L V6                                            9
2.0L Turbo Inline-4                                9
1.6L Turbocharged 4-Cylinder                       9
V8 Petrol                                          9
3.0L Twin-Turbo V6                                 8
2.9L V6 Twin Turbo                                 8
2.0L Turbo Inline-4 Gasoline                       8
1.5L Turbo I4                                      7
3.8L Twin-Turbo Flat-6                             7
2.9L Twin-Turbo V6                                 7
3.6L V6 engine                                     7
2.5L 4-Cylinder                                    7
Hybrid I4                                          7
2.0L MIVEC                                         7
2.4L Diesel Turbo                                  7
I4 + ELECTRIC                                      6
2.5L Inline-4                                      6
2.5L V6                                            6
Single Electric Motor                              6
1.5L Turbo Inline-4 Gasoline                       6
6.6L V8 Diesel                                     6
5.3L V8 engine                                     6
6.6L V8 engine                                     6
6.2L V8 engine                                     6
ELECTRIC MOTOR                                     5
1.5L I4 Turbo                                      5
3.8L Twin-Turbo V6                                 5
4.0L Twin-Turbo V8                                 5
Permanent Magnet Synchronous                       5
3.6L V6 Pentastar Gasoline                         5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
Turbocharged V6                                    5
1.2L MIVEC                                         5
0.7L 3-Cylinder                                    5
2.0L SkyActiv-G                                    5
3.3L V6                                            4
3.0L V6 Turbo Diesel                               4
Diesel I4                                          4
1.2L Diesel I3                                     4
1.0L I3 Turbo                                      4
1.4L I4 Turbo + Electric Motor                     4
1.0L Turbocharged Inline-3                         4
660cc Inline-3                                     4
3.0L V6 Turbo                                      4
4.0L V8 Twin Turbo                                 4
1.2L Revotron 3-cylinder Petrol                    4
1.4L CR4 Diesel                                    4
2.7L Turbo 4-cylinder                              4
1.6L 4-Cylinder                                    4
Hybrid I4 + Electric Motor                         4
1.6L 4-Cylinder Hybrid                             4
1.6L Hybrid Turbocharged 4-Cylinder                4
12.8L I6 Turbo Diesel                              4
Twin-Turbo V6 Hybrid                               4
2.0L EcoBoost                                      4
3.2L Diesel Turbo                                  4
2.5L SkyActiv-G                                    4
ELECTRIC                                           3
1.2L,4-CYLINDER,INLINE-4(I4)                       3
2.8L,TURBO,DIESEL                                  3
1.0L Turbo I3                                      3
1.6L Diesel                                        3
4.0L V6                                            3
2.0L Turbo Diesel I4                               3
1.6L I4 Gas                                        3
2.0L Diesel                                        3
3.7L V6                                            3
1.5L Turbo Inline-3                                3
5.0L V8                                            3
2.4L Inline-4                                      3
2.5L Inline-4 Diesel                               3
4.5L V8                                            3
4.0L Twin-Turbo V8 + Electric Motor                3
2.7L Turbo Inline-4 Gasoline                       3
1.2L Revotron Petrol                               3
Tri Electric Motors                                3
Dual Electric Motors (AWD)                         3
6.2L Supercharged V8 Gasoline                      3
1.4L Inline-4 Gasoline                             3
1.5L Turbo 4-cylinder                              3
1.5L Turbocharged I4 engine                        3
2.5L Turbocharged 4-Cylinder                       3
I4 Turbocharged                                    3
1.5L EcoBoost                                      3
2.0L Hybrid                                        3
2.0L                                               3
2.5L Hybrid                                        3
2.7L V6                                            3
EcoBlue Turbo Diesel                               3
1.5L MIVEC                                         3
2.5L Turbocharged                                  3
1.3L Inline-4                                      3
1.2L Petrol                                        2
BOXER-4                                            2
2.0L,4-CYLINDER,INLINE-4(I4)                       2
2.2L,4-CYLINDER,INLINE-4(I4)                       2
1.6L,TURBOCHARGED INLINE-3                         2
Plug-in Hybrid                                     2
1.2L I4 Turbo                                      2
1.4L I4 Gas                                        2
1.2L I4 Gas                                        2
4.0L V8 Turbo Diesel                               2
1.4L I4 Turbo                                      2
1.8L I4 Gas                                        2
1.5L Inline-4 Diesel                               2
3.0L V6 Twin-Turbo                                 2
4.8L Inline-6                                      2
2.3L Inline-4 Diesel                               2
1.5L Turbo Hybrid                                  2
3.0L Inline-4 Diesel                               2
2.4L Inline-6                                      2
2.9L V6 + Electric Motor                           2
4.0L V8 + Electric Motor                           2
2.0L Turbo Flat-4                                  2
2.9L Twin-Turbo V6 + Electric Motor                2
3.0L Turbocharged V6                               2
3.0L V6 + Electric Motor                           2
1.5L Diesel                                        2
1.3L Quadrajet Diesel                              2
1.4L Petrol                                        2
2.0L Kryotec Turbocharged Diesel                   2
2.2L Dicor Diesel                                  2
Single Electric Motor (RWD)                        2
2.0L Turbo PHEV                                    2
1.3L Turbo PHEV                                    2
4.3L V6 Gasoline                                   2
Dual-Motor Electric                                2
2.5L I4 engine                                     2
13.0L I6 Turbo Diesel                              2
V6 Hybrid                                          2
1.0L EcoBoost                                      2
1.5L                                               2
2.3L EcoBoost                                      2
3.5L EcoBoost                                      2
7.3L V8                                            2
6.7L Turbo-Diesel                                  2
2.3L Turbo Inline-4                                2
3.5L Twin-Turbo V6                                 2
Turbocharged Inline-4                              2
Turbocharged V8 Diesel                             2
V8 Gasoline Engine                                 2
I4 Hybrid                                          2
2.4L Hybrid                                        2
1.5L Turbo                                         2
1.6L MIVEC                                         2
2.2L Diesel                                        2
1.8L MIVEC                                         2
HYBRID                                             1
1.4L,4-CYLINDER,INLINE-4(I4)                       1
1.5L,4-CYLINDER,INLINE(I4)                         1
2.0L,4-CYLINDER,WITH HYBRID SYSTEM                 1
3.3L,V6,TWIN TURBO DIESEL                          1
3.5L,V6,HYBRID TWIN-TURBO                          1
2.0L,INLINE-4                                      1
HYDROGEN FUEL CELL,ELECTRIC MOTOR                  1
2.5L,INLINE-4,HYBRID,OR 3.5L,V6                    1
2.0L HYBRID                                        1
4.0L,DIESEL                                        1
1.5L,HYBRID                                        1
1.0L,INLINE-3                                      1
3.5L,V6,PLUG IN HYBRID                             1
1.8L,HYBRID                                        1
1.6L PETROL + PLUG IN HYBRID SYSTEM                1
2.5L Turbocharged Inline-4                         1
1.6L PETROL                                        1
2.5L Turbo Diese                                   1
1.6L Turbo GDI 4-cylinder                          1
4.0L V8                                            1
Plug-in Hybrid V6                                  1
Electric AWD                                       1
1.4L I3 Gas                                        1
2.9L VR6                                           1
3.0L V6 Diesel                                     1
6.0L W12 Gas                                       1
1.5L I4 Gas                                        1
Diesel                                             1
1.9L I4 Diesel                                     1
3.6L V6 Gas                                        1
2.0L I4 Turbo Diesel                               1
1.4L I4 Diesel                                     1
Plug-in Hybrid (1.4L I4 Turbo)                     1
3.2L VR6                                           1
1.6L Turbocharged Rally Engine                     1
Plug-in Hybrid (0.8L I2 Diesel)                    1
1.5L I4 CNG                                        1
Gasoline                                           1
1.3L Turbocharged Inline-4                         1
1.5L Turbocharged Inline-3                         1
1.2L Inline-3 Hybrid                               1
1.2L Turbocharged Inline-4                         1
1.2L Inline-3                                      1
2.0L Inline-4 Hybrid                               1
2.0L Inline-6                                      1
2.5L Inline-4 Hybrid                               1
1.3L Turbo Hybrid Inline-4                         1
1.6L Turbo Inline-4                                1
2.6L Twin-Turbo Inline-6                           1
2.0L VC-Turbo Inline-4                             1
1.4L Inline-4                                      1
2.8L Inline-6 Diesel                               1
2.7L Inline-4 Diesel                               1
3.0L Twin-Turbo V6 Hybrid                          1
3.5L Twin-Turbo V8                                 1
1.0L Turbo Inline-4                                1
1.5L Hybrid                                        1
1.2L Hybrid                                        1
2.7L Turbo Diesel                                  1
4.2L Inline-6                                      1
4.1L V8                                            1
2.8L Inline-6                                      1
1.8L Turbo Inline-4                                1
3.0L Flat-6 Twin Turbo                             1
2.0L Turbocharged Flat-4                           1
2.5L Turbocharged Flat-4                           1
3.0L Turbo Diesel V6                               1
3.0L Twin-Turbo V6 Gasoline                        1
4.2L Naturally Aspirated Flat-6                    1
1.2L Turbocharged Petrol                           1
1.2L Revotron Bi-Fuel                              1
624cc MPFI                                         1
1.2L MPFI Petrol                                   1
1.4L MPFI Petrol                                   1
1.2L Turbo Petrol                                  1
2.2L Varicor Diesel                                1
3.0L CR4 Diesel                                    1
Quad Electric Motors                               1
2.0L Turbo I4 Gasoline                             1
2.4L I4 Tigershark Gasoline                        1
2.0L Turbo Gasoline                                1
1.3L Turbo I4 Gasoline                             1
5.7L V8 Gasoline with eTorque                      1
6.4L V8 Gasoline                                   1
1.5L 4-Cylinder                                    1
5.7L V8 Gasoline                                   1
3.2L V6 Pentastar Gasoline                         1
6.4L V8 HEMI Gasoline                              1
3.6L Twin-Turbo V6 Gasoline                        1
1.4L Turbo Inline-4 Gasoline                       1
6.6L V8 Gasoline                                   1
1.3L Turbo Inline-3 Gasoline                       1
2.8L Turbo Diesel I4                               1
1.2L Turbo Inline-3 Gasoline                       1
2.5L Inline-4 Gasoline                             1
2.0L Turbo 4-cylinder                              1
2.7L Turbo engine                                  1
4.3L V6 engine                                     1
Electric motors with advanced AWD                  1
3.3L Turbocharged V6                               1
2.5L Hybrid Turbocharged 4-Cylinder                1
Hybrid I4+ Electric Motor                          1
16.1L I6 Turbo Diesel                              1
7.7L I6 Turbo Diesel                               1
5.1L I4 Turbo Diesel                               1
I4 Petrol + Electric Motor                         1
Inline-4 Hybrid                                    1
Inline-4 Turbocharged                              1
Turbocharged I4                                    1
1.0L Turbo Inline-3                                1
5.4L V8                                            1
6.2L V8                                            1
2.5L Inline-4 + Electric                           1
3.3L V6 + Electric                                 1
2.7L Twin-Turbo V6                                 1
Turbocharged Inline-3                              1
Naturally Aspirated V6                             1
Inline-4 Gasoline Engine                           1
Supercharged V8                                    1
Naturally Aspirated V8                             1
V6 Hybrid + Electric Motor                         1
I4 Turbo Diesel                                    1
V6 EcoBoost                                        1
V6 Turbocharged                                    1
2.0L Turbocharged                                  1
2.2L Diesel Turbo                                  1
1.1L                                               1
2.4L MIVEC                                         1
3.0L Diesel                                        1
2.4L PHEV                                          1
7.5L Diesel                                        1
3.0L Diesel Hybrid                                 1
2.4L Petrol                                        1
2.4L 4-Cylinder                                    1
1.5L Turbocharged                                  1
3.3L Inline-6 Turbo                                1
2.3L Turbocharged                                  1
2.5L Diesel                                        1
3.2L Turbo Diesel                                  1
1.5L SkyActiv-G                                    1
2.3L Miller Cycle V6                               1
657cc Turbocharged Inline-3                        1
2.6L Inline-4                                      1
3.0L Inline-4                                      1
3.0L Inline-6                                      1
1.2L Inline-4                                      1
0.36L Inline-2                                     1
0.66L Inline-3                                     1
2.5L Hybrid I4                                     1
2.4L Turbo I4 (i-FORCE MAX Hybrid)                 1
2.0L Gas                                           1
1.8L                                               1

### Creating `electric_motors` column
Counts the electric motors of fully electric vehicles from keywords in the description (`single` = 1, `dual` = 2, `tri` = 3, `quad` = 4). Electric engines that don't state a number default to 1, and non-electric engines get 0. Word boundaries (`\b`) prevent `tri` from matching inside `electric`.

In [35]:
number_of_electric_motors = text.str.extract(r"\b(single|dual|tri|quad)\b")[0].map(
    {"single":1, "dual":2, "tri":3, "quad":4}
)

df["electric_motors"] = np.where(df["is_electric"] == 1, number_of_electric_motors.fillna(1), 0).astype(int)

In [36]:
print(df.loc[df["electric_motors"] > 0, "Engines_cleaned"].value_counts().to_string())

Engines_cleaned
Dual Electric Motors                              23
Electric Motor                                    21
Electric                                          16
Single Electric Motor                              6
ELECTRIC MOTOR                                     5
Permanent Magnet Synchronous                       5
Electric motors with up to 11,500 lb-ft torque     5
Electric (Dual Motor)                              5
ELECTRIC                                           3
Tri Electric Motors                                3
Dual Electric Motors (AWD)                         3
Single Electric Motor (RWD)                        2
Dual-Motor Electric                                2
HYDROGEN FUEL CELL,ELECTRIC MOTOR                  1
Electric AWD                                       1
Quad Electric Motors                               1
Electric motors with advanced AWD                  1

In [37]:
df.loc[df["is_electric"] == 1, "displacement"] = 0

In [38]:
df["displacement"].isna().sum()

np.int64(371)

# `CC/BatteryCapacity_cleaned` column

In [39]:
print(df["CC/BatteryCapacity_cleaned"].value_counts().to_string())

CC/BatteryCapacity_cleaned
2,000 cc                                            31
1984 cc                                             31
2,500 cc                                            25
1591 cc                                             22
3996 cc                                             20
1,998 cc                                            19
6200 cc                                             18
3600 cc                                             18
5552 cc                                             17
2894 cc                                             17
1,598 cc                                            16
2981 cc                                             16
1,500 cc                                            16
5300 cc                                             16
6,592 cc                                            15
1998 cc                                             15
2,400 cc                                            15
5,204 cc                                            14
6,749 cc                                            14
1,499 cc                                            14
3,000 cc                                            14
3,500 cc                                            13
1968 cc                                             12
6,498 cc                                            11
2,480 cc                                            11
2000 cc                                             11
1999 cc (I4)                                        11
1498 cc                                             10
77 kWh                                              10
1199 cc                                             10
1999 cc                                             10
1,598 cc (petrol) + Electric Motor                  10
7993 cc                                             10
1,199 cc                                            10
1,200 cc                                             9
1598 cc                                              9
1500 cc                                              9
1999 cc (I4)                                         9
 2995 cc (V6)                                        9
2,996 cc                                             8
1,600 cc                                             8
93.4 kWh                                             8
100 kWh                                              8
200 kWh                                              8
5000 cc (V8)                                         8
660 cc                                               8
3,996 cc                                             7
2,995 cc                                             7
999 cc                                               7
2995 cc                                              7
2997 cc                                              7
3745 cc                                              7
2700 cc                                              7
6600 cc                                              7
3,564 cc                                             7
1,800 cc                                             7
1,308 cc                                             7
3,900 cc                                             6
1,991 cc                                             6
1,984 cc                                             6
1,496 cc                                             6
3498 cc                                              6
87 kWh                                               6
1497 cc                                              6
2960 cc                                              6
1396 cc                                              6
5,327 cc                                             6
6,600 cc                                             6
6,162 cc                                             6
3778 cc                                              6
77.4 kWh                                             6
2995 cc (V6)                                         6
3,982 cc                                             5
2,993 cc                                             5
1,995 cc                                             5
1,798 cc                                             5
3,456 cc                                             5
2967 cc                                              5
 1968 cc                                             5
3799 cc                                              5
79.2 kWh                                             5
2500 cc                                              5
3500 cc                                              5
90 kWh (Battery)                                     5
3,500 cc (V6)                                        5
1,000 - 2,000 cc                                     5
3,200 cc                                             5
2,488 cc                                             4
3,993 cc                                             4
2,494 cc                                             4
1,490 cc                                             4
3,300 cc                                             4
1498 cc                                              4
999 cc                                               4
1395 cc                                              4
1997 cc                                              4
2498 cc                                              4
17.9 kWh Battery                                     4
1400 cc                                              4
66 kWh                                               4
12800 cc                                             4
2,200 cc                                             4
1,500 - 2,000 cc                                     4
2,300 - 2,700 cc                                     4
1,300 cc                                             4
2,998 cc                                             3
5,663 cc                                             3
5,935 cc                                             3
4,395 cc                                             3
1,969 cc                                             3
1,498 cc                                             3
1,986 cc                                             3
1,497 cc                                             3
1,197 cc                                             3
1,997 cc                                             3
2,755 cc                                             3
3,800 cc                                             3
 1598 cc                                             3
3954 cc                                              3
 1498 cc                                             3
1390 cc                                              3
 1984 cc                                             3
1798 cc                                              3
1198 cc                                              3
3696 cc                                              3
2488 cc                                              3
1597 cc                                              3
4494 cc                                              3
1988 cc                                              3
3995 cc                                              3
2179 cc                                              3
50 kWh                                               3
1,500 cc (I4)                                        3
3,493 cc                                             3
3,300 - 5,000 cc                                     3
6,200 - 7,300 cc                                     3
2,300 cc                                             3
6,496 cc                                             2
3,799 cc                                             2
3,498 cc                                             2
4,935 cc                                             2
95 kwh                                               2
1,996 cc                                             2
1,600 cc                                             2
 13.8 kwh                                            2
3,956 cc                                             2
2,179 cc                                             2
1,618 cc                                             2
1,987 cc                                             2
32.3 kWh                                             2
2967 cc                                              2
1395 cc                                              2
 1199 cc                                             2
1197 cc                                              2
1598 cc                                              2
1781 cc                                              2
1332 cc                                              2
1461 cc                                              2
4750 cc                                              2
2298 cc                                              2
3000 cc                                              2
1595 cc                                              2
2389 cc                                              2
2393 cc                                              2
24 kWh                                               2
1199 cc                                              2
 1497 cc                                             2
1248 cc                                              2
1956 cc                                              2
82 kWh                                               2
1300 cc                                              2
5700 cc                                              2
6400 cc                                              2
17.3 kWh                                             2
11.4 kWh                                             2
4300 cc                                              2
212 kWh                                              2
13000 cc                                             2
1,560 cc                                             2
-                                                    2
2,000 - 3,500 cc                                     2
1,000 - 1,500 cc                                     2
1,500 - 2,500 cc                                     2
2,000 - 2,700 cc                                     2
2,300 - 3,000 cc                                     2
3,500 - 5,400 cc                                     2
6,700 - 7,300 cc                                     2
2,500 - 2,000 cc                                     2
5,000 cc                                             2
2,700 cc                                             2
1,000 cc                                             2
6,700 cc                                             2
5,200 cc                                             2
2,500 cc (petrol) + Electric Motor                   2
16 kWh battery                                       2
1,100 - 1,500 cc                                     2
1,600 - 2,000 cc                                     2
2,000 - 2,200 cc                                     2
657 cc                                               2
2487 cc + batt                                       2
3990 cc                                              1
6749 cc                                              1
3,994 cc                                             1
6496 cc                                              1
2,387 cc                                             1
3,696 cc                                             1
5,598 cc                                             1
3,998 cc                                             1
1991 cc                                              1
5,980 cc                                             1
11.6 kwh                                             1
 1.49 kwh                                            1
1,598 cc                                             1
3,471 cc                                             1
2,694 cc                                             1
64.8 kwh (Base Model),72.8 kwh (Higher End Model     1
1,396 cc                                             1
1,999 cc                                             1
1,462 cc                                             1
3,346 cc                                             1
3,445 cc                                             1
1.24 kwh                                             1
HYBRID(2,494 cc),V6(3,456 cc)                        1
4,009 cc                                             1
998 cc                                               1
75 KWH                                               1
65 KWH                                               1
72.6 KWH                                             1
1,591 cc                                             1
53.6 kwh(Standard Range)                             1
 77.4 kwh(Long Range)                                1
39.2 kwh                                             1
1.56 kwh                                             1
 40 - 58 kWh                                         1
 3956 cc                                             1
58 - 77 kWh                                          1
58 kWh                                               1
2861 cc                                              1
 5998 cc                                             1
1192 cc                                              1
1198 cc                                              1
 1390 cc                                             1
35.8 kWh                                             1
 1896 cc                                             1
1984 cc                                              1
 3597 cc                                             1
~50 kWh (Estimate)                                   1
1395 cc + Electric Motor                             1
3956 cc                                              1
3189 cc                                              1
800 cc + Electric Motor                              1
1395 cc + Battery                                    1
1197 cc                                              1
1796 cc                                              1
5026 cc                                              1
1838 cc                                              1
2438 cc                                              1
2568 cc                                              1
1397 cc                                              1
2825 cc                                              1
2664 cc                                              1
3495 cc                                              1
987 cc                                               1
2999 cc                                              1
659 cc                                               1
1770 cc                                              1
1769 cc                                              1
2663 cc                                              1
4169 cc                                              1
3275 cc                                              1
4130 cc                                              1
2753 cc                                              1
1809 cc                                              1
1839 cc                                              1
2953 cc                                              1
2497 cc                                              1
95 kWh                                               1
4194 cc                                              1
624 cc                                               1
1193 cc                                              1
26 kWh                                               1
 1368 cc                                             1
40.5 kWh                                             1
2956 cc                                              1
30.2 kWh                                             1
60 kWh                                               1
75 kWh                                               1
2400 cc                                              1
3200 cc                                              1
2800 cc                                              1
1200 cc                                              1
2,713 cc                                             1
4,300 cc                                             1
1,599 cc (petrol) + Electric Motor                   1
3300 cc                                              1
1,599 cc (Petrol) + Electric Motor                   1
16100 cc                                             1
7700 cc                                              1
5100 cc                                              1
1998 cc (I4)                                         1
1999 cc (I4) + Electric                              1
3,493 cc (V6)                                        1
2,400 cc (I4)                                        1
Battery (68-98 kWh)                                  1
Battery (98 kWh)                                     1
7,300 cc                                             1
89 kWh (Electric)                                    1
3,000 cc (petrol) + Electric Motor                   1
2,400 cc                                             1
 20 kWh battery                                      1
7,500 cc                                             1
35.5 kWh battery                                     1
2,600 cc                                             1
1,588 cc                                             1
1,590 cc                                             1
360 cc                                               1
1,298 cc                                             1
2,620 cc                                             1
2487 cc                                              1
2393 cc + Battery                                    1
1987 cc                                              1
 Hybrid batt                                         1
1798                                                 1
 1987 cc + batt                                      1

Checking that rows with only battery capacity (no `cc`) have `is_electric = 1`. The few exceptions are hybrids/PHEVs with a combustion engine, so no correction is needed.

In [40]:
col = df["CC/BatteryCapacity_cleaned"]
with_battery = col.str.contains(r"(?i)kwh|battery|batt", na=False)
with_cc = col.str.contains(r"(?i)\bcc\b", na=False)

rows_with_only_battery = with_battery & ~with_cc

df.loc[rows_with_only_battery, "is_electric"].value_counts()

is_electric
1    100
0     13
Name: count, dtype: int64

All exceptions are hybrids/PHEVs (`is_hybrid = 1`) with a combustion engine, so `is_electric = 0` is correct.

In [41]:
mask = rows_with_only_battery & (df["is_electric"] == 0)
df.loc[mask, ["Engines_cleaned", "CC/BatteryCapacity_cleaned", "is_hybrid", "cylinders", "displacement"]]

,Engines_cleaned,CC/BatteryCapacity_cleaned,is_hybrid,cylinders,displacement
184,I4 + ELECTRIC,13.8 kwh,1,4.0,NaN
192,I4 + ELECTRIC,1.49 kwh,1,4.0,NaN
194,I4 + ELECTRIC,13.8 kwh,1,4.0,NaN
561,2.9L V6 + Electric Motor,17.9 kWh Battery,1,6.0,2.9
562,2.9L V6 + Electric Motor,17.9 kWh Battery,1,6.0,2.9
563,4.0L V8 + Electric Motor,17.9 kWh Battery,1,8.0,4.0
570,4.0L V8 + Electric Motor,17.9 kWh Battery,1,8.0,4.0
711,2.0L Turbo PHEV,17.3 kWh,1,NaN,2.0
712,2.0L Turbo PHEV,17.3 kWh,1,NaN,2.0
713,1.3L Turbo PHEV,11.4 kWh,1,NaN,1.3
714,1.3L Turbo PHEV,11.4 kWh,1,NaN,1.3
1132,2.4L Hybrid,20 kWh battery,1,NaN,2.4
1281,2.0L Hybrid,Hybrid batt,1,NaN,2.0

### Removing `kwh` rows from `CC/Battery_cleaned` and creating `kwh_capacity`

There are not individual columns with `kwh` and `cc` together

In [42]:
with_kwh = col.str.contains(r"(?i)kwh", na=False)
(with_kwh & with_cc).sum()

np.int64(0)

Identifying rows that contain `kWh` and creating the `kwh_capacity` column. Rows that do not contain `kWh` are set to 0.

In [43]:
rows_with_kwh = df["CC/BatteryCapacity_cleaned"].str.contains(r"(?i)kwh")
df["kwh_capacity"] = df["CC/BatteryCapacity_cleaned"].where(rows_with_kwh, 0)

Verifying that rows that contains `kwh` in `BatteryCapacity_cleaned` column are the ones with the entire value

In [44]:
df.loc[df["CC/BatteryCapacity_cleaned"].str.contains(r"(?i)kwh"), "kwh_capacity"].value_counts()

kwh_capacity
77 kWh                                              10
93.4 kWh                                             8
100 kWh                                              8
200 kWh                                              8
87 kWh                                               6
77.4 kWh                                             6
79.2 kWh                                             5
90 kWh (Battery)                                     5
17.9 kWh Battery                                     4
66 kWh                                               4
50 kWh                                               3
95 kwh                                               2
 13.8 kwh                                            2
32.3 kWh                                             2
24 kWh                                               2
82 kWh                                               2
17.3 kWh                                             2
11.4 kWh                                             2
212 kWh                                              2
16 kWh battery                                       2
11.6 kwh                                             1
 1.49 kwh                                            1
64.8 kwh (Base Model),72.8 kwh (Higher End Model     1
1.24 kwh                                             1
75 KWH                                               1
65 KWH                                               1
72.6 KWH                                             1
53.6 kwh(Standard Range)                             1
 77.4 kwh(Long Range)                                1
39.2 kwh                                             1
1.56 kwh                                             1
 40 - 58 kWh                                         1
58 - 77 kWh                                          1
58 kWh                                               1
35.8 kWh                                             1
~50 kWh (Estimate)                                   1
95 kWh                                               1
26 kWh                                               1
40.5 kWh                                             1
30.2 kWh                                             1
60 kWh                                               1
75 kWh                                               1
Battery (68-98 kWh)                                  1
Battery (98 kWh)                                     1
89 kWh (Electric)                                    1
 20 kWh battery                                      1
35.5 kWh battery                                     1
Name: count, dtype: int64

In `CC/BatteryCapacity_cleaned` set rows with kwh to `"0"`

In [45]:
df.loc[rows_with_kwh, "CC/BatteryCapacity_cleaned"] = "0"

### Handle cylinders mistmatch

There is a mismatch in the number of cylinders on row `932`.  
In `CC/BatteryCapacity_cleaned` has `V6(6)`, in `Engines_cleaned` has `V8(8)` and in `cylinders` has `8`

In [46]:
df.loc[df["CC/BatteryCapacity_cleaned"].str.contains(r"(?i)v"), ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "cylinders"]]

        CC/BatteryCapacity_cleaned                  Engines_cleaned  cylinders
241  HYBRID(2,494 cc),V6(3,456 cc)  2.5L,INLINE-4,HYBRID,OR 3.5L,V6        6.0
931                   2995 cc (V6)                               V6        6.0
932                   2995 cc (V6)                        V8 Petrol        8.0
935                   2995 cc (V6)                        V6 Petrol        6.0
939                   2995 cc (V6)                        V6 Petrol        6.0
942                   2995 cc (V6)                        V6 Petrol        6.0
944                   5000 cc (V8)                        V8 Petrol        8.0
946                   5000 cc (V8)                        V8 Petrol        8.0
949                   2995 cc (V6)                        V6 Petrol        6.0
950                   2995 cc (V6)                        V6 Petrol        6.0
951                   5000 cc (V8)                        V8 Petrol        8.0
954                   5000 cc (V8)                        V8 Petrol        8.0
956                   2995 cc (V6)                        V6 Petrol        6.0
959                   2995 cc (V6)                        V6 Petrol        6.0
963                   2995 cc (V6)                        V6 Petrol        6.0
964                   5000 cc (V8)                        V8 Petrol        8.0
966                   2995 cc (V6)                        V6 Petrol        6.0
968                   2995 cc (V6)                        V6 Petrol        6.0
970                   2995 cc (V6)                        V6 Petrol        6.0
972                   2995 cc (V6)                        V6 Petrol        6.0
973                   5000 cc (V8)                        V8 Petrol        8.0
976                   2995 cc (V6)                        V6 Petrol        6.0
977                   5000 cc (V8)                        V8 Petrol        8.0
978                   5000 cc (V8)                        V8 Petrol        8.0
981                  3,493 cc (V6)             Twin-Turbo V6 Hybrid        6.0
982                  3,500 cc (V6)                               V6        6.0
983                  3,500 cc (V6)                               V6        6.0
986                  3,500 cc (V6)                               V6        6.0
988                  3,500 cc (V6)                               V6        6.0
990                  3,500 cc (V6)                               V6        6.0

Make sure row `932` is the only one with a mismatch in cylinders.  
Is the only one

In [47]:
batteryCapacity_cleaned_V = df["CC/BatteryCapacity_cleaned"].str.extract(r"(?i)(v\d+)")[0]
engines_cleaned_V = df["Engines_cleaned"].str.extract(r"(?i)(v\d+)")[0]
mismatch = batteryCapacity_cleaned_V.notna() & engines_cleaned_V.notna() & (batteryCapacity_cleaned_V != engines_cleaned_V)

df.loc[mismatch, ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "cylinders"]]

    CC/BatteryCapacity_cleaned Engines_cleaned  cylinders
932               2995 cc (V6)       V8 Petrol        8.0

Looking for the car name of the row `932`.  
It is `jaguar f-type`

In [48]:
df.loc[mismatch, ["Cars Names", "CC/BatteryCapacity_cleaned", "Engines_cleaned", "cylinders"]]

        Cars Names CC/BatteryCapacity_cleaned Engines_cleaned  cylinders
932  jaguar f-type               2995 cc (V6)       V8 Petrol        8.0

A `jaguar f-type` with `2995cc` is more likely to have `6` cylinders.  
Replace cylinder values in `Engines_cleaned` and `cylinders` columns from `8` to `6`

In [49]:
df.loc[932, "Engines_cleaned"] = "V6 Petrol"
df.loc[932, "cylinders"] = 6.0
df.loc[[932]]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,...,CC/BatteryCapacity_cleaned,displacement,cylinders,is_turbo,is_hybrid,is_diesel,is_electric,is_rotatory,electric_motors,kwh_capacity
932,jaguar land rover,jaguar f-type,V6 / V8 Petrol,2995 cc (V6),335 hp,260 km/h,5.1 sec,"$70,000",Petrol,2,...,2995 cc (V6),NaN,6.0,False,0,0,0,0,0,0

### Handle `HYBRID(2,494 cc),V6(3,456 cc)` in `CC/BatteryCapacity_cleaned` column

There are a hybrid and gasoline values for the same car

In [50]:
df.loc[df["CC/BatteryCapacity_cleaned"].str.contains("HYBRID(2,494 cc),V6(3,456 cc)", regex=False), ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "Engines"]]

,CC/BatteryCapacity_cleaned,Engines_cleaned,Engines
241,"HYBRID(2,494 cc),V6(3,456 cc)","2.5L,INLINE-4,HYBRID,OR 3.5L,V6","2.5L,INLINE-4,HYBRID,OR 3.5L,V6"

Make a manual `explode`  
Separing the `hybrid` and `gasoline` values into differents rows, and deleting the old row `(241)`

In [51]:
row = df.loc[[241]]
hybrid_row, gasoline_row = row.copy(), row.copy() 

hybrid_row["Engines_cleaned"] = "2.5L Inline-4 Hybrid",
hybrid_row["CC/BatteryCapacity_cleaned"] = "2,494 cc" 
hybrid_row[["displacement", "cylinders", "is_hybrid"]] = [2.5, 4, 1] 

gasoline_row["Engines_cleaned"] = "3.5L V6",
gasoline_row["CC/BatteryCapacity_cleaned"] = "3,456 cc" 
gasoline_row[["displacement", "cylinders", "is_hybrid"]] = [3.5, 6, 0] 

df = pd.concat([df.drop(index=241), hybrid_row, gasoline_row]).reset_index(drop=True)

The `explode` on `Engines` column copied the whole `cc` ranges (e.g., `1,500 - 2,000 cc`) into each resulting row. Each row must keep only its own value.

In [52]:
df.loc[df["CC/BatteryCapacity_cleaned"].str.contains(r"(?=.*cc)(?=.*-)"), ["Engines", "Engines_cleaned", "CC/BatteryCapacity_cleaned"]]

,Engines,Engines_cleaned,CC/BatteryCapacity_cleaned
1055,1.5L EcoBoost / 2.0L Hybrid,1.5L EcoBoost,"1,500 - 2,000 cc"
1056,1.5L EcoBoost / 2.0L Hybrid,2.0L Hybrid,"1,500 - 2,000 cc"
1057,3.5L V6 / 2.0L EcoBoost,3.5L V6,"2,000 - 3,500 cc"
1058,3.5L V6 / 2.0L EcoBoost,2.0L EcoBoost,"2,000 - 3,500 cc"
1059,1.0L EcoBoost / 1.5L,1.0L EcoBoost,"1,000 - 1,500 cc"
1060,1.0L EcoBoost / 1.5L,1.5L,"1,000 - 1,500 cc"
1061,1.0L EcoBoost / 1.5L / 2.0L,1.0L EcoBoost,"1,000 - 2,000 cc"
1062,1.0L EcoBoost / 1.5L / 2.0L,1.5L,"1,000 - 2,000 cc"
1063,1.0L EcoBoost / 1.5L / 2.0L,2.0L,"1,000 - 2,000 cc"
1065,1.0L Turbo Inline-3 / 2.0L,1.0L Turbo Inline-3,"1,000 - 2,000 cc"
1066,1.0L Turbo Inline-3 / 2.0L,2.0L,"1,000 - 2,000 cc"
1067,1.5L EcoBoost / 2.5L Hybrid,1.5L EcoBoost,"1,500 - 2,500 cc"
1068,1.5L EcoBoost / 2.5L Hybrid,2.5L Hybrid,"1,500 - 2,500 cc"
1069,2.0L EcoBoost / 2.7L V6,2.0L EcoBoost,"2,000 - 2,700 cc"
1070,2.0L EcoBoost / 2.7L V6,2.7L V6,"2,000 - 2,700 cc"
1071,2.3L EcoBoost / 3.0L V6,2.3L EcoBoost,"2,300 - 3,000 cc"
1072,2.3L EcoBoost / 3.0L V6,3.0L V6,"2,300 - 3,000 cc"
1073,3.5L EcoBoost / 5.4L V8,3.5L EcoBoost,"3,500 - 5,400 cc"
1074,3.5L EcoBoost / 5.4L V8,5.4L V8,"3,500 - 5,400 cc"
1075,2.3L EcoBoost / 2.7L V6,2.3L EcoBoost,"2,300 - 2,700 cc"
1076,2.3L EcoBoost / 2.7L V6,2.7L V6,"2,300 - 2,700 cc"
1077,1.5L EcoBoost / 2.0L EcoBoost,1.5L EcoBoost,"1,500 - 2,000 cc"
1078,1.5L EcoBoost / 2.0L EcoBoost,2.0L EcoBoost,"1,500 - 2,000 cc"
1079,3.3L V6 / 5.0L V8 / 3.5L EcoBoost,3.3L V6,"3,300 - 5,000 cc"
1080,3.3L V6 / 5.0L V8 / 3.5L EcoBoost,5.0L V8,"3,300 - 5,000 cc"
1081,3.3L V6 / 5.0L V8 / 3.5L EcoBoost,3.5L EcoBoost,"3,300 - 5,000 cc"
1082,6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel,6.2L V8,"6,200 - 7,300 cc"
1083,6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel,7.3L V8,"6,200 - 7,300 cc"
1084,6.2L V8 / 7.3L V8 / 6.7L Turbo-Diesel,6.7L Turbo-Diesel,"6,200 - 7,300 cc"
1085,6.7L Turbo-Diesel / 7.3L V8,6.7L Turbo-Diesel,"6,700 - 7,300 cc"
1086,6.7L Turbo-Diesel / 7.3L V8,7.3L V8,"6,700 - 7,300 cc"
1087,2.5L Hybrid / 2.0L EcoBoost,2.5L Hybrid,"2,500 - 2,000 cc"
1088,2.5L Hybrid / 2.0L EcoBoost,2.0L EcoBoost,"2,500 - 2,000 cc"
1089,2.3L Turbo Inline-4 / 2.7L V6,2.3L Turbo Inline-4,"2,300 - 2,700 cc"
1090,2.3L Turbo Inline-4 / 2.7L V6,2.7L V6,"2,300 - 2,700 cc"
1141,1.1L / 1.5L MIVEC,1.1L,"1,100 - 1,500 cc"
1142,1.1L / 1.5L MIVEC,1.5L MIVEC,"1,100 - 1,500 cc"
1153,1.6L MIVEC / 2.0L,1.6L MIVEC,"1,600 - 2,000 cc"
1154,1.6L MIVEC / 2.0L,2.0L,"1,600 - 2,000 cc"
1158,2.0L Diesel / 2.2L Diesel,2.0L Diesel,"2,000 - 2,200 cc"
1159,2.0L Diesel / 2.2L Diesel,2.2L Diesel,"2,000 - 2,200 cc"

Each car already has its engine size in the `displacement` column.  
For rows whose range combines two engines (e.g., `2,000 - 2,200 cc`), take each row's `displacement`, multiply it by `1000` and convert it to `str`.  

Before: `2,000 - 2,200 cc` (in both rows)<br>
After: `2000 cc` (row 1), `2200 cc` (row 2)

In [53]:
mask = df["CC/BatteryCapacity_cleaned"].str.contains(r"(?=.*cc)(?=.*-)")

df.loc[mask, "CC/BatteryCapacity_cleaned"] = (df.loc[mask, "displacement"] * 1000).astype(int).astype(str) + " cc"

In [54]:
df.loc[[1055, 1056]]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,...,CC/BatteryCapacity_cleaned,displacement,cylinders,is_turbo,is_hybrid,is_diesel,is_electric,is_rotatory,electric_motors,kwh_capacity
1055,ford,fusion (mondeo),1.5L EcoBoost / 2.0L Hybrid,"1,500 - 2,000 cc",160 - 250 hp,220 km/h,7.5 sec,"$25,000 - $40,000",Petrol/Hybrid,5,...,1500 cc,1.5,NaN,True,0,0,0,0,0,0
1056,ford,fusion (mondeo),1.5L EcoBoost / 2.0L Hybrid,"1,500 - 2,000 cc",160 - 250 hp,220 km/h,7.5 sec,"$25,000 - $40,000",Petrol/Hybrid,5,...,2000 cc,2.0,NaN,False,1,0,0,0,0,0

### Removing `(V#)`, `(I#)`, `cc`, `comas (,)` from `CC/BatteryCapacity_cleaned`

Some rows contain `(V#)` or `(I#)` values (e.g., `V6`, `I4`). This information is already in the `Engines_cleaned` and `cylinders` columns, so it is removed from `CC/BatteryCapacity_cleaned`.  
Before: `2,500 cc (V6)`, `3,400 cc (I4)`   
After: `2,500 cc`, `3,400 cc`

In [55]:
df["CC/BatteryCapacity_cleaned"] = df["CC/BatteryCapacity_cleaned"].str.replace(r"(?i)\s*\([vi]\d+\)\s*", "", regex=True).str.strip()
df["CC/BatteryCapacity_cleaned"] = df["CC/BatteryCapacity_cleaned"].str.replace(r"(?i)\s*cc\s*", "", regex = True)
df["CC/BatteryCapacity_cleaned"] = df["CC/BatteryCapacity_cleaned"].str.replace(",", "")

has_number = df["CC/BatteryCapacity_cleaned"].str.contains(r"\d", na=False) 
df.loc[has_number, "CC/BatteryCapacity_cleaned"] = df.loc[has_number, "CC/BatteryCapacity_cleaned"].str.extract(r"\s*(\d+)\s*", expand=False)

In [65]:
df["displacement", ""].head()

0    NaN
1    NaN
2    1.2
3    NaN
4    NaN
Name: displacement, dtype: float64

In [70]:
df[df["Engines_cleaned"] == "V6 EcoBoost"]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,...,CC/BatteryCapacity_cleaned,displacement,cylinders,is_turbo,is_hybrid,is_diesel,is_electric,is_rotatory,electric_motors,kwh_capacity
1125,ford,bronco (2024),V6 EcoBoost,"2,700 cc",310 hp,200 km/h,6.7 sec,"$45,000",Petrol,5,...,2700,NaN,6.0,True,0,0,0,0,0,0

### In `CC/BatteryCapacity_cleaned` are `0` values where it is suppossed to be a `cc` value

In [57]:
mask = (
    df["CC/BatteryCapacity_cleaned"].str.contains(r"-|\b0\b") & 
    df["CC/Battery Capacity"].str.contains("cc") 
)
df.loc[mask, ["CC/Battery Capacity", "CC/BatteryCapacity_cleaned"]]
#df.loc[df["CC/BatteryCapacity_cleaned"].str.contains(r"-|\b0\b")]

            CC/Battery Capacity CC/BatteryCapacity_cleaned
184         1,600 cc / 13.8 kwh                          0
192         1,600 cc / 1.49 kwh                          0
194         1,598 cc / 13.8 kwh                          0
275       1498 cc / 40 - 58 kWh                          0
1131  2,400 cc / 20 kWh battery                          0

Look in the original column `CC/Battery Capacity` to just take the `cc` value and pass it to `CC/BatteryCapacity_cleaned`

In [58]:
df.loc[mask, "CC/BatteryCapacity_cleaned"] =  (
    df.loc[mask, "CC/Battery Capacity"].str.extract(r"(?i)(\d+,?\d+)\s*cc", expand=False)
)

In [59]:
df.loc[mask, ["CC/Battery Capacity", "CC/BatteryCapacity_cleaned"]]

            CC/Battery Capacity CC/BatteryCapacity_cleaned
184         1,600 cc / 13.8 kwh                      1,600
192         1,600 cc / 1.49 kwh                      1,600
194         1,598 cc / 13.8 kwh                      1,598
275       1498 cc / 40 - 58 kWh                       1498
1131  2,400 cc / 20 kWh battery                      2,400

### The mayority of rows with `CC/BatteryCapacity_cleaned` in `0` is because they are `electric cars`. But, there are `8 rows` in `Engines_cleaned` which have `displacement` values `(e.g 2.9L)`

In [60]:
mask = (
    (df["CC/BatteryCapacity_cleaned"] == "0") & 
    (df["displacement"] != 0)
)
df.loc[mask, ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "displacement"]]

    CC/BatteryCapacity_cleaned           Engines_cleaned  displacement
560                          0  2.9L V6 + Electric Motor           2.9
561                          0  2.9L V6 + Electric Motor           2.9
562                          0  4.0L V8 + Electric Motor           4.0
569                          0  4.0L V8 + Electric Motor           4.0
710                          0           2.0L Turbo PHEV           2.0
711                          0           2.0L Turbo PHEV           2.0
712                          0           1.3L Turbo PHEV           1.3
713                          0           1.3L Turbo PHEV           1.3

Let's use it´s `displacement` value to multiply it `1,000` times to get the `cc` value  
Before: `2.9L`  
After: `2,900 (cc value)`

In [61]:
mask = (
    (df["CC/BatteryCapacity_cleaned"] == "0") & 
    (df["displacement"] != 0)
)

df.loc[mask, "CC/BatteryCapacity_cleaned"] = (df.loc[mask, "displacement"] * 1000).astype(str)

In [62]:
df.loc[mask, ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "displacement"]]

    CC/BatteryCapacity_cleaned           Engines_cleaned  displacement
560                     2900.0  2.9L V6 + Electric Motor           2.9
561                     2900.0  2.9L V6 + Electric Motor           2.9
562                     4000.0  4.0L V8 + Electric Motor           4.0
569                     4000.0  4.0L V8 + Electric Motor           4.0
710                     2000.0           2.0L Turbo PHEV           2.0
711                     2000.0           2.0L Turbo PHEV           2.0
712                     1300.0           1.3L Turbo PHEV           1.3
713                     1300.0           1.3L Turbo PHEV           1.3

### There are `90` values set at `0` in `CC/BatteryCapacity_cleaned` column. Let's verify if its correct

All the cars are electric, so a `0` in `CC/BatteryCapacity_cleaned` it's correct

In [ ]:
print(df.loc[df["CC/BatteryCapacity_cleaned"] == '0', ["CC/BatteryCapacity_cleaned", "Engines_cleaned", "is_electric", "is_hybrid"]].to_string())

In [ ]:
print(df["CC/BatteryCapacity_cleaned"].value_counts().to_string())

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1287 entries, 0 to 1286
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Company Names               1287 non-null   object
 1   Cars Names                  1287 non-null   object
 2   Engines                     1287 non-null   object
 3   CC/Battery Capacity         1284 non-null   object
 4   HorsePower                  1287 non-null   object
 5   Total Speed                 1287 non-null   object
 6   Performance(0 - 100 )KM/H   1281 non-null   object
 7   Cars Prices                 1287 non-null   object
 8   Fuel Types                  1287 non-null   object
 9   Seats                       1287 non-null   object
 10  Torque                      1286 non-null   object
 11  Engines_cleaned             1287 non-null   str
 12  CC/BatteryCapacity_cleaned  1284 non-null   str
 13  displacement                916 non-null    float64
 14  cylinders                   1125 non-null   float64
 15  is_turbo                    1287 non-null   bool
 16  is_hybrid                   1287 non-null   int64
 17  is_diesel                   1287 non-null   int64
 18  is_electric                 1287 non-null   int64
 19  is_rotatory                 1287 non-null   int64
 20  electric_motors             1287 non-null   int64
 21  kwh_capacity                1287 non-null   object
dtypes: bool(1), float64(2), int64(5), object(12), str(2)
memory usage: 212.5+ KB